const discounts = {
  // Page titles
  pageTitle: 'Quản lý Giảm giá',
  pageSubtitle: 'Quản lý chương trình khuyến mãi và ưu đãi đặc biệt',
  addPageTitle: 'Thêm Giảm giá mới',
  addPageSubtitle: 'Tạo chương trình giảm giá cho sản phẩm',
  editPageTitle: 'Chỉnh sửa Giảm giá',
  
  // Navigation
  backToDiscounts: 'Quay lại Giảm giá',
  
  // Stats
  totalDiscounts: 'Tổng Giảm giá',
  activeDiscounts: 'Đang hoạt động',
  expiredDiscounts: 'Đã hết hạn',
  wideScopeOffers: 'Ưu đãi Đa sản phẩm',
  discountsApplyingToMultiple: '{{count}} giảm giá áp dụng cho nhiều sản phẩm',
  
  // Table headers
  code: 'Mã',
  discount: 'Giảm giá',
  type: 'Loại',
  value: 'Giá trị',
  scope: 'Phạm vi',
  validFrom: 'Hiệu lực từ',
  validTo: 'Đến',
  minPurchase: 'Đơn tối thiểu',
  maxUses: 'Giới hạn',
  
  // Discount types
  percentage: 'Phần trăm',
  percentageOff: 'Giảm theo %',
  fixedAmount: 'Số tiền cố định',
  fixedAmountOff: 'Giảm Số tiền',
  buyXGetY: 'Mua X Tặng Y',
  freeShipping: 'Miễn phí vận chuyển',
  
  // Discount type descriptions
  discountType: 'Loại Giảm giá',
  discountByPercentage: 'Giảm giá theo phần trăm',
  fixedDiscountAmount: 'Giảm giá cố định',
  buyXItemsGetYFree: 'Mua X sản phẩm, tặng Y miễn phí',
  percentageDesc: 'Giảm giá theo phần trăm',
  fixedAmountDesc: 'Giảm giá cố định',
  buyXGetYDesc: 'Mua X sản phẩm, tặng Y miễn phí',
  
  // Application scope
  specificProduct: 'Sản phẩm cụ thể',
  allProducts: 'Tất cả sản phẩm',
  specificCategory: 'Danh mục cụ thể',
  selectedProducts: 'Sản phẩm đã chọn',
  scopeProduct: 'Sản phẩm',
  scopeAll: 'Tất cả',
  scopeCategory: 'Danh mục',
  scopeSelected: 'Đã chọn',
  
  // Status
  active: 'Hoạt động',
  inactive: 'Không hoạt động',
  finished: 'Đã kết thúc',
  expired: 'Hết hạn',
  scheduled: 'Đã lên lịch',
  
  // Buttons
  addDiscount: 'Thêm Giảm giá',
  createDiscount: 'Tạo Giảm giá',
  updateDiscount: 'Cập nhật Giảm giá',
  deleteDiscount: 'Xóa Giảm giá',
  saveAsDraft: 'Lưu bản nháp',
  activate: 'Kích hoạt',
  deactivate: 'Vô hiệu hóa',
  duplicate: 'Nhân bản',
  
  // Bulk actions
  activateSales: 'Kích hoạt Khuyến mãi',
  deactivateSales: 'Vô hiệu hóa Khuyến mãi',
  activatingCount: 'Đang kích hoạt {{count}} khuyến mãi...',
  deactivatingCount: 'Đang vô hiệu hóa {{count}} khuyến mãi...',
  activatedCount: 'Đã kích hoạt thành công {{count}} giảm giá',
  deactivatedCount: 'Đã vô hiệu hóa thành công {{count}} giảm giá',
  failedToActivate: 'Không thể kích hoạt giảm giá',
  failedToDeactivate: 'Không thể vô hiệu hóa giảm giá',
  exportingCount: 'Đang xuất {{count}} giảm giá...',
  
  // Form sections
  basicInformation: 'Thông tin Cơ bản',
  basicInfo: 'Thông tin Cơ bản',
  discountTypeValue: 'Loại & Giá trị Giảm giá',
  applicationScope: 'Phạm vi Áp dụng',
  
  // Edit/Add page headings
  editDiscount: 'Chỉnh sửa Giảm giá',
  addDiscountPageTitle: 'Thêm Giảm giá mới',
  discountSummary: 'Tóm tắt Giảm giá',
  advancedOptions: 'Tùy chọn Nâng cao',
  discountRules: 'Quy tắc Giảm giá',
  usageLimits: 'Giới hạn Sử dụng',
  validityPeriod: 'Thời gian Hiệu lực',
  
  // Form fields
  discountId: 'Mã Giảm giá',
  discountName: 'Tên Giảm giá',
  description: 'Mô tả',
  startDate: 'Ngày bắt đầu',
  endDate: 'Ngày kết thúc',
  discountPercentage: 'Phần trăm Giảm giá',
  discountAmount: 'Số tiền Giảm giá',
  autoGenerated: 'Tự động tạo',
  generatedFromNameAndDate: 'Tạo từ tên và ngày',
  buyQuantity: 'Số lượng Mua',
  getQuantity: 'Số lượng Tặng',
  getFreeProduct: 'Sản phẩm Tặng',
  sameProduct: 'Cùng sản phẩm',
  differentProduct: 'Sản phẩm khác',
  selectProduct: 'Chọn sản phẩm',
  selectCategory: 'Chọn danh mục',
  selectProductsToDiscount: 'Chọn sản phẩm để giảm giá',
  searchProducts: 'Tìm kiếm sản phẩm...',
  searchCategories: 'Tìm kiếm danh mục...',
  noProducts: 'Không tìm thấy sản phẩm',
  noCategories: 'Không tìm thấy danh mục',
  
  // Placeholders
  placeholderName: 'VD: Khuyến mãi Hè 2024',
  placeholderDescription: 'Mô tả chương trình giảm giá và điều khoản...',
  placeholderPercentage: '10',
  placeholderFixedAmount: '120.00',
  placeholderFixedAmountCzk: '120',
  placeholderFixedAmountEur: '4.80',
  placeholderBuyQuantity: '2',
  placeholderGetQuantity: '1',
  
  // Validation messages
  nameRequired: 'Tên giảm giá là bắt buộc',
  startDateRequired: 'Ngày bắt đầu là bắt buộc',
  endDateRequired: 'Ngày kết thúc là bắt buộc',
  percentageRequired: 'Phần trăm là bắt buộc',
  fixedAmountRequired: 'Số tiền là bắt buộc',
  productRequired: 'Sản phẩm là bắt buộc',
  categoryRequired: 'Danh mục là bắt buộc',
  fillRequiredFields: 'Vui lòng điền đầy đủ thông tin bắt buộc cho loại và phạm vi giảm giá đã chọn',
  pleaseFixErrors: 'Vui lòng sửa các lỗi sau trước khi gửi:',
  
  // Tooltips
  tooltipDiscounts: '{{count}} giảm giá',
  tooltipActive: '{{count}} giảm giá đang hoạt động',
  tooltipExpired: '{{count}} giảm giá đã hết hạn',
  
  // Product selection
  addProduct: 'Thêm sản phẩm',
  removeProduct: 'Xóa sản phẩm',
  productsSelected: 'Đã chọn {{count}} sản phẩm',
  alreadySelected: 'Đã được chọn',
  productInList: 'Sản phẩm {{count}}',
  productsInCategory: '{{count}} sản phẩm',
  
  // Scope selection messages
  selectScopeFirst: 'Vui lòng chọn phạm vi áp dụng trước',
  selectProductFirst: 'Chọn sản phẩm để áp dụng giảm giá này',
  selectCategoryFirst: 'Chọn danh mục để áp dụng giảm giá này',
  selectProductsFirst: 'Chọn sản phẩm để áp dụng giảm giá này',
  allProductsSelected: 'Giảm giá này áp dụng cho tất cả sản phẩm',
  appliesTo: 'Áp dụng cho',
  
  // Buy X Get Y options
  customerGets: 'Khách hàng nhận',
  sameProductFree: 'Cùng sản phẩm miễn phí',
  differentProductFree: 'Sản phẩm khác miễn phí',
  
  // Advanced options
  autoConversion: 'Tự động chuyển đổi sau 1.5 giây',
  approxRate: 'Tỷ giá ước tính: 1 EUR = 25 CZK',
  
  // Messages
  loadingDiscounts: 'Đang tải giảm giá...',
  failedToLoad: 'Không thể tải giảm giá',
  discountCreated: 'Tạo giảm giá thành công',
  discountUpdated: 'Cập nhật giảm giá thành công',
  discountDeleted: 'Xóa giảm giá thành công',
  discountDuplicated: 'Nhân bản giảm giá thành công',
  failedToCreate: 'Không thể tạo giảm giá',
  failedToUpdate: 'Không thể cập nhật giảm giá',
  failedToDelete: 'Không thể xóa giảm giá',
  cannotDelete: 'Không thể xóa giảm giá - đang được sử dụng trong các bản ghi hiện tại',
  deletedCount: 'Đã xóa {{count}} giảm giá thành công',
  
  // Export
  exportReport: 'Báo cáo Giảm giá',
  exportFilename: 'Giam-gia_{{date}}',
  exportedToXLSX: 'Đã xuất {{count}} giảm giá ra XLSX',
  exportedToPDF: 'Đã xuất {{count}} giảm giá ra PDF',
  exportFailed: 'Không thể xuất giảm giá',
  exportFailedXLSX: 'Không thể xuất giảm giá ra XLSX',
  exportFailedPDF: 'Không thể xuất giảm giá ra PDF',
  
  // Export columns
  exportCode: 'Mã',
  exportDescription: 'Mô tả',
  exportType: 'Loại',
  exportValue: 'Giá trị',
  exportMinPurchase: 'Đơn tối thiểu',
  exportMaxUses: 'Giới hạn',
  exportValidFrom: 'Hiệu lực từ',
  exportValidUntil: 'Đến',
  exportStatus: 'Trạng thái',
  unlimited: 'Không giới hạn',
  buyXGetYFormat: 'M{{buy}}T{{get}}',
  
  // Empty states
  noDiscounts: 'Không tìm thấy giảm giá',
  noDiscountsDescription: 'Bắt đầu bằng cách tạo giảm giá đầu tiên',
  
  // Delete confirmation
  deleteConfirmTitle: 'Xóa Giảm giá',
  deleteConfirmDescription: 'Bạn có chắc chắn muốn xóa giảm giá này? Hành động này không thể hoàn tác.',
  deleteConfirmMultiple: 'Bạn có chắc chắn muốn xóa {{count}} giảm giá? Hành động này không thể hoàn tác.',
  
  // Currency
  currencyCZK: 'CZK',
  currencyEUR: 'EUR',
  
  // Required field marker
  required: '*',
  
  // Column visibility
  toggleColumns: 'Hiển thị cột',
  
  // Additional display fields (used in AllDiscounts card view)
  usageLimit: 'Giới hạn sử dụng',
  usesCount: '{{count}} lần sử dụng',
  none: 'Không có',
  restrictions: 'Hạn chế',
  noDiscountsFound: 'Không tìm thấy giảm giá',
  tryAdjustingSearch: 'Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc',
  deleteDiscounts: 'Xóa Giảm giá',
  confirmDelete: 'Bạn có chắc chắn muốn xóa {{count}} giảm giá?',
  
  // Edit/Add page summary
  enterName: 'Nhập tên giảm giá',
  discountValue: 'Giá trị Giảm giá',
  itemPrice: 'Giá sản phẩm',
  finalPrice: 'Giá cuối cùng',
  promotion: 'Khuyến mãi',
  buyGetFree: 'Mua {{buy}}, Tặng {{get}} Miễn phí',
  effectiveDiscount: 'Giảm giá hiệu quả',
  onTotalItems: 'trên tổng {{total}} sản phẩm',
  
  // Set Sale Price discount type
  setSalePrice: 'Đặt Giá Sale',
  setNewPriceDescription: 'Đặt giá bán mới cố định cho sản phẩm',
  newSalePrice: 'Giá Sale Mới',
  salePriceCzk: 'Giá Sale (CZK)',
  salePriceEur: 'Giá Sale (EUR)',
  placeholderSalePriceCzk: 'VD: 299',
  placeholderSalePriceEur: 'VD: 12',
  originalPrice: 'Giá gốc',
  salePrice: 'Giá Sale',
  youSave: 'Bạn tiết kiệm',
  specificProductNotSelected: 'Chọn sản phẩm',
} as const;

export default discounts;
