import { pgTable, varchar, text, integer, timestamp, foreignKey, boolean, numeric, date, serial, jsonb, json, unique, pgEnum } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const currency = pgEnum("currency", ['CZK', 'EUR', 'USD', 'VND', 'CNY'])
export const discountType = pgEnum("discount_type", ['flat', 'rate'])
export const expenseStatus = pgEnum("expense_status", ['pending', 'overdue', 'paid'])
export const locationType = pgEnum("location_type", ['ZONE', 'AISLE', 'RACK', 'SHELF', 'BIN', 'STAGE', 'DOCK'])
export const orderPriority = pgEnum("order_priority", ['low', 'medium', 'high'])
export const orderStatus = pgEnum("order_status", ['pending', 'to_fulfill', 'picking', 'packing', 'ready_to_ship', 'shipped'])
export const paymentMethod = pgEnum("payment_method", ['Bank Transfer', 'PayPal', 'COD', 'Cash'])
export const paymentStatus = pgEnum("payment_status", ['pending', 'paid', 'pay_later'])
export const purchaseStatus = pgEnum("purchase_status", ['purchased', 'processing', 'ready_to_ship', 'shipped', 'delivered'])
export const recurring = pgEnum("recurring", ['daily', 'weekly', 'monthly', 'yearly'])
export const returnStatus = pgEnum("return_status", ['awaiting', 'processing', 'completed'])
export const temperatureType = pgEnum("temperature_type", ['ambient', 'cool', 'warm'])
export const warehouseStatus = pgEnum("warehouse_status", ['active', 'inactive', 'maintenance', 'rented'])


export const stockAdjustmentRequests = pgTable("stock_adjustment_requests", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	locationId: varchar("location_id").notNull(),
	requestedBy: varchar("requested_by"),
	adjustmentType: text("adjustment_type").notNull(),
	currentQuantity: integer("current_quantity").notNull(),
	requestedQuantity: integer("requested_quantity").notNull(),
	reason: text().notNull(),
	status: text().default('pending').notNull(),
	approvedBy: varchar("approved_by"),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	rejectionReason: text("rejection_reason"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const supplierFiles = pgTable("supplier_files", {
	id: text().primaryKey().notNull(),
	supplierId: text("supplier_id"),
	fileName: text("file_name").notNull(),
	fileType: text("file_type").notNull(),
	fileUrl: text("file_url").notNull(),
	fileSize: integer("file_size"),
	uploadedBy: text("uploaded_by"),
	uploadedAt: timestamp("uploaded_at", { mode: 'string' }).defaultNow().notNull(),
	mimeType: text("mime_type"),
}, (table) => [
	foreignKey({
			columns: [table.supplierId],
			foreignColumns: [suppliers.id],
			name: "supplier_files_supplier_id_suppliers_id_fk"
		}).onDelete("cascade"),
]);

export const ticketComments = pgTable("ticket_comments", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	ticketId: varchar("ticket_id").notNull(),
	content: text().notNull(),
	isInternal: boolean("is_internal").default(false),
	createdBy: varchar("created_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const warehouseLayouts = pgTable("warehouse_layouts", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	warehouseId: text("warehouse_id").notNull(),
	name: text().notNull(),
	width: numeric({ precision: 10, scale:  2 }).notNull(),
	length: numeric({ precision: 10, scale:  2 }).notNull(),
	coordinateSystem: text("coordinate_system").default('grid').notNull(),
	generatedAt: timestamp("generated_at", { mode: 'string' }).defaultNow().notNull(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const tickets = pgTable("tickets", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	ticketId: varchar("ticket_id").notNull(),
	customerId: varchar("customer_id"),
	orderId: varchar("order_id"),
	title: varchar().notNull(),
	description: text(),
	category: varchar().notNull(),
	status: varchar().default('open').notNull(),
	priority: varchar().default('medium').notNull(),
	assignedTo: varchar("assigned_to"),
	createdBy: varchar("created_by"),
	resolvedAt: timestamp("resolved_at", { mode: 'string' }),
	dueDate: timestamp("due_date", { mode: 'string' }),
	tags: text().array(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const warehouseFiles = pgTable("warehouse_files", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	warehouseId: text("warehouse_id").notNull(),
	fileName: text("file_name").notNull(),
	fileType: text("file_type").notNull(),
	fileUrl: text("file_url").notNull(),
	fileSize: integer("file_size").notNull(),
	uploadedBy: varchar("uploaded_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.warehouseId],
			foreignColumns: [warehouses.id],
			name: "warehouse_files_warehouse_id_warehouses_id_fk"
		}).onDelete("cascade"),
]);

export const userActivities = pgTable("user_activities", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	userId: varchar("user_id"),
	action: varchar({ length: 255 }).notNull(),
	entityType: varchar("entity_type", { length: 100 }),
	entityId: varchar("entity_id", { length: 255 }),
	description: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const warehouseFinancialContracts = pgTable("warehouse_financial_contracts", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	warehouseId: text("warehouse_id").notNull(),
	contractName: text("contract_name").notNull(),
	contractType: text("contract_type").default('rental').notNull(),
	price: numeric({ precision: 10, scale:  2 }).default('0').notNull(),
	currency: text().default('CZK').notNull(),
	billingPeriod: text("billing_period").default('monthly').notNull(),
	customBillingDays: integer("custom_billing_days"),
	rentalDueDate: date("rental_due_date"),
	startDate: date("start_date"),
	endDate: date("end_date"),
	status: text().default('active'),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const warehouseTasks = pgTable("warehouse_tasks", {
	id: serial().primaryKey().notNull(),
	title: text().notNull(),
	description: text(),
	type: varchar({ length: 50 }).default('general').notNull(),
	priority: varchar({ length: 20 }).default('medium').notNull(),
	status: varchar({ length: 20 }).default('pending').notNull(),
	dueAt: timestamp("due_at", { mode: 'string' }),
	assignedToUserId: varchar("assigned_to_user_id"),
	createdByUserId: varchar("created_by_user_id").notNull(),
	completedAt: timestamp("completed_at", { mode: 'string' }),
	completedByUserId: varchar("completed_by_user_id"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const stockAdjustmentHistory = pgTable("stock_adjustment_history", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	locationId: varchar("location_id").notNull(),
	adjustmentType: text("adjustment_type").notNull(),
	previousQuantity: integer("previous_quantity").notNull(),
	adjustedQuantity: integer("adjusted_quantity").notNull(),
	newQuantity: integer("new_quantity").notNull(),
	reason: text().notNull(),
	source: text().notNull(),
	referenceId: varchar("reference_id"),
	adjustedBy: varchar("adjusted_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const suppliers = pgTable("suppliers", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar({ length: 255 }).notNull(),
	contactPerson: varchar("contact_person", { length: 255 }),
	email: varchar({ length: 255 }),
	phone: varchar({ length: 20 }),
	address: text(),
	country: varchar({ length: 100 }),
	website: varchar({ length: 255 }),
	supplierLink: text("supplier_link"),
	lastPurchaseDate: timestamp("last_purchase_date", { mode: 'string' }),
	totalPurchased: numeric("total_purchased", { precision: 12, scale:  2 }).default('0'),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const users = pgTable("users", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	email: varchar(),
	firstName: varchar("first_name"),
	lastName: varchar("last_name"),
	profileImageUrl: varchar("profile_image_url"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	role: varchar(),
	phoneNumber: varchar("phone_number"),
	replitSub: varchar("replit_sub"),
	username: varchar(),
	passwordHash: text("password_hash"),
});

export const purchaseItems = pgTable("purchase_items", {
	id: serial().primaryKey().notNull(),
	purchaseId: integer("purchase_id").notNull(),
	name: text().notNull(),
	sku: text(),
	quantity: integer().notNull(),
	unitPrice: numeric("unit_price", { precision: 10, scale:  2 }),
	weight: numeric({ precision: 10, scale:  3 }),
	dimensions: text(),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	totalPrice: numeric("total_price", { precision: 10, scale:  2 }),
	status: text().default('ordered'),
	trackingNumber: text("tracking_number"),
	warehouseLocation: text("warehouse_location"),
	consolidationId: integer("consolidation_id"),
	imageUrl: text("image_url"),
	hsCode: text("hs_code"),
	dutyRatePercent: numeric("duty_rate_percent", { precision: 5, scale:  2 }),
	unitGrossWeightKg: numeric("unit_gross_weight_kg", { precision: 10, scale:  3 }),
	unitLengthCm: numeric("unit_length_cm", { precision: 10, scale:  2 }),
	unitWidthCm: numeric("unit_width_cm", { precision: 10, scale:  2 }),
	unitHeightCm: numeric("unit_height_cm", { precision: 10, scale:  2 }),
	landingCostUnitBase: numeric("landing_cost_unit_base", { precision: 12, scale:  4 }),
	processingTimeDays: integer("processing_time_days"),
	unitType: text("unit_type").default('selling'),
	unitName: text("unit_name"),
	quantityInSellingUnits: integer("quantity_in_selling_units"),
});

export const productBundles = pgTable("product_bundles", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	bundleId: varchar("bundle_id", { length: 100 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	sku: varchar({ length: 100 }),
	priceCzk: varchar("price_czk", { length: 20 }),
	priceEur: varchar("price_eur", { length: 20 }),
	discountPercentage: varchar("discount_percentage", { length: 10 }),
	notes: text(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	imageUrl: varchar("image_url", { length: 500 }),
});

export const employeeIncidents = pgTable("employee_incidents", {
	id: serial().primaryKey().notNull(),
	employeeId: integer("employee_id").notNull(),
	title: text().notNull(),
	description: text(),
	type: varchar({ length: 50 }).default('mistake').notNull(),
	severity: varchar({ length: 20 }).default('minor').notNull(),
	status: varchar({ length: 20 }).default('open').notNull(),
	occurredAt: timestamp("occurred_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	resolvedAt: timestamp("resolved_at", { mode: 'string' }),
	resolvedBy: varchar("resolved_by"),
	resolution: text(),
	reportedBy: varchar("reported_by"),
	relatedOrderId: varchar("related_order_id"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
});

export const warehouses = pgTable("warehouses", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar({ length: 255 }).notNull(),
	location: varchar({ length: 255 }),
	address: text(),
	city: varchar({ length: 100 }),
	country: varchar({ length: 100 }).default('Czech Republic'),
	zipCode: varchar("zip_code", { length: 20 }),
	phone: varchar({ length: 20 }),
	email: varchar({ length: 255 }),
	manager: varchar({ length: 255 }),
	capacity: integer().default(0),
	type: varchar({ length: 50 }).default('branch'),
	status: warehouseStatus().default('active'),
	rentedFromDate: timestamp("rented_from_date", { mode: 'string' }),
	expenseId: varchar("expense_id", { length: 255 }),
	contact: varchar({ length: 255 }),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	floorArea: numeric("floor_area", { precision: 10, scale:  2 }),
	code: varchar({ length: 20 }),
	totalAisles: integer("total_aisles").default(6),
	maxRacks: integer("max_racks").default(10),
	maxLevels: integer("max_levels").default(5),
	maxBins: integer("max_bins").default(5),
	aisleConfigs: jsonb("aisle_configs"),
	zones: jsonb(),
});

export const orderCartonItems = pgTable("order_carton_items", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	planId: varchar("plan_id").notNull(),
	cartonNumber: integer("carton_number").notNull(),
	cartonId: varchar("carton_id"),
	orderItemId: varchar("order_item_id"),
	productId: varchar("product_id"),
	quantity: integer().notNull(),
	itemWeightKg: numeric("item_weight_kg", { precision: 10, scale:  2 }).notNull(),
	aiEstimated: boolean("ai_estimated").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const packingMaterialUsage = pgTable("packing_material_usage", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	materialId: varchar("material_id").notNull(),
	quantity: integer().notNull(),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const databaseBackups = pgTable("database_backups", {
	id: serial().primaryKey().notNull(),
	backupType: varchar("backup_type", { length: 20 }).default('manual').notNull(),
	status: varchar({ length: 20 }).default('in_progress').notNull(),
	fileName: varchar("file_name", { length: 255 }),
	filePath: text("file_path"),
	fileSize: integer("file_size"),
	tablesIncluded: text("tables_included").array(),
	recordCount: integer("record_count"),
	triggeredBy: varchar("triggered_by"),
	errorMessage: text("error_message"),
	startedAt: timestamp("started_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	completedAt: timestamp("completed_at", { mode: 'string' }),
	expiresAt: timestamp("expires_at", { mode: 'string' }),
});

export const session = pgTable("session", {
	sid: varchar().primaryKey().notNull(),
	sess: json().notNull(),
	expire: timestamp({ precision: 6, mode: 'string' }).notNull(),
});

export const invoices = pgTable("invoices", {
	id: serial().primaryKey().notNull(),
	orderId: varchar("order_id"),
	posSaleId: varchar("pos_sale_id"),
	invoiceNumber: varchar("invoice_number", { length: 100 }).notNull(),
	pdfUrl: text("pdf_url"),
	status: varchar({ length: 50 }).default('draft').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("invoices_invoice_number_unique").on(table.invoiceNumber),
]);

export const activityLog = pgTable("activity_log", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id"),
	action: varchar().notNull(),
	entityType: varchar("entity_type"),
	entityId: varchar("entity_id"),
	description: text().notNull(),
	metadata: jsonb(),
	ipAddress: varchar("ip_address"),
	userAgent: text("user_agent"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const aiLocationSuggestions = pgTable("ai_location_suggestions", {
	id: serial().primaryKey().notNull(),
	productId: varchar("product_id"),
	customItemId: integer("custom_item_id"),
	locationCode: text("location_code").notNull(),
	zone: text().notNull(),
	accessibilityLevel: text("accessibility_level").notNull(),
	reasoning: text().notNull(),
	metadata: jsonb(),
	generatedAt: timestamp("generated_at", { mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const appSettings = pgTable("app_settings", {
	key: varchar().primaryKey().notNull(),
	value: jsonb().notNull(),
	category: varchar().default('general'),
	description: text(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	updatedBy: varchar("updated_by"),
});

export const bundleItems = pgTable("bundle_items", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	bundleId: varchar("bundle_id").notNull(),
	productId: varchar("product_id"),
	variantId: varchar("variant_id"),
	quantity: integer().notNull(),
	productName: varchar("product_name", { length: 255 }),
	variantName: varchar("variant_name", { length: 255 }),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
});

export const consolidations = pgTable("consolidations", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	shippingMethod: text("shipping_method").notNull(),
	warehouse: text().notNull(),
	notes: text(),
	targetWeight: numeric("target_weight", { precision: 10, scale:  3 }),
	maxItems: integer("max_items"),
	status: text().default('preparing').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	location: text(),
});

export const consolidationItems = pgTable("consolidation_items", {
	id: serial().primaryKey().notNull(),
	consolidationId: integer("consolidation_id").notNull(),
	itemId: integer("item_id").notNull(),
	itemType: text("item_type").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const customItems = pgTable("custom_items", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	source: text().notNull(),
	orderNumber: text("order_number"),
	quantity: integer().default(1).notNull(),
	unitPrice: numeric("unit_price", { precision: 10, scale:  2 }).default('0'),
	weight: numeric({ precision: 10, scale:  3 }).default('0'),
	dimensions: text(),
	trackingNumber: text("tracking_number"),
	notes: text(),
	customerName: text("customer_name"),
	customerEmail: text("customer_email"),
	status: text().default('available').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	classification: text().default('general'),
	purchaseOrderId: integer("purchase_order_id"),
	orderItems: json("order_items"),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
});

export const costAllocations = pgTable("cost_allocations", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id").notNull(),
	customItemId: integer("custom_item_id").notNull(),
	costType: text("cost_type").notNull(),
	basis: text().notNull(),
	amountAllocatedBase: numeric("amount_allocated_base", { precision: 12, scale:  4 }).notNull(),
	detailsJson: jsonb("details_json"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const customerBadges = pgTable("customer_badges", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	customerId: varchar("customer_id").notNull(),
	orderId: varchar("order_id"),
	badgeType: varchar("badge_type").notNull(),
	scope: varchar().default('customer').notNull(),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const customerBillingAddresses = pgTable("customer_billing_addresses", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	customerId: varchar("customer_id").notNull(),
	firstName: varchar("first_name"),
	lastName: varchar("last_name"),
	company: varchar(),
	email: varchar(),
	tel: varchar(),
	street: varchar(),
	streetNumber: varchar("street_number"),
	city: varchar(),
	zipCode: varchar("zip_code"),
	country: varchar(),
	isPrimary: boolean("is_primary").default(false),
	label: varchar(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	vatId: varchar("vat_id"),
	ico: varchar(),
});

export const categories = pgTable("categories", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	nameEn: text("name_en"),
	nameCz: text("name_cz"),
	nameVn: text("name_vn"),
});

export const dailySequences = pgTable("daily_sequences", {
	id: serial().primaryKey().notNull(),
	orderType: varchar("order_type", { length: 10 }).notNull(),
	date: date().notNull(),
	currentSequence: integer("current_sequence").default(0).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const deliveryHistory = pgTable("delivery_history", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id"),
	carrier: text().notNull(),
	origin: text().notNull(),
	destination: text().notNull(),
	shippingMethod: text("shipping_method").notNull(),
	dispatchedAt: timestamp("dispatched_at", { mode: 'string' }).notNull(),
	deliveredAt: timestamp("delivered_at", { mode: 'string' }).notNull(),
	estimatedDays: integer("estimated_days"),
	actualDays: integer("actual_days").notNull(),
	seasonalFactor: boolean("seasonal_factor").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const employees = pgTable("employees", {
	id: serial().primaryKey().notNull(),
	employeeId: varchar("employee_id").notNull(),
	firstName: varchar("first_name").notNull(),
	lastName: varchar("last_name").notNull(),
	email: varchar(),
	phone: varchar(),
	address: text(),
	position: varchar().notNull(),
	department: varchar().notNull(),
	hireDate: date("hire_date").notNull(),
	terminationDate: date("termination_date"),
	status: varchar().default('active').notNull(),
	salary: numeric({ precision: 10, scale:  2 }).notNull(),
	paymentFrequency: varchar("payment_frequency").default('monthly').notNull(),
	currency: varchar().default('CZK').notNull(),
	bankAccount: varchar("bank_account"),
	bankName: varchar("bank_name"),
	taxId: varchar("tax_id"),
	insuranceId: varchar("insurance_id"),
	emergencyContact: varchar("emergency_contact"),
	emergencyPhone: varchar("emergency_phone"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	userId: varchar("user_id"),
});

export const importPurchases = pgTable("import_purchases", {
	id: serial().primaryKey().notNull(),
	supplier: text().notNull(),
	trackingNumber: text("tracking_number"),
	estimatedArrival: timestamp("estimated_arrival", { mode: 'string' }),
	notes: text(),
	shippingCost: numeric("shipping_cost", { precision: 10, scale:  2 }).default('0'),
	totalCost: numeric("total_cost", { precision: 10, scale:  2 }).default('0'),
	status: text().default('pending').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	paymentCurrency: text("payment_currency").default('USD'),
	totalPaid: numeric("total_paid", { precision: 10, scale:  2 }).default('0'),
	purchaseCurrency: text("purchase_currency").default('USD'),
	purchaseTotal: numeric("purchase_total", { precision: 10, scale:  2 }).default('0'),
	exchangeRate: numeric("exchange_rate", { precision: 10, scale:  6 }).default('1'),
	location: text().default('China'),
	shippingCurrency: text("shipping_currency").default('USD'),
	consolidation: text().default('No'),
});

export const customers = pgTable("customers", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar({ length: 255 }).notNull(),
	facebookName: varchar("facebook_name", { length: 255 }),
	facebookId: varchar("facebook_id", { length: 255 }),
	email: varchar({ length: 255 }),
	phone: varchar({ length: 20 }),
	address: text(),
	city: varchar({ length: 100 }),
	zipCode: varchar("zip_code", { length: 20 }),
	country: varchar({ length: 100 }),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	type: varchar({ length: 50 }).default('regular'),
	vatId: varchar("vat_id", { length: 50 }),
	taxId: varchar("tax_id", { length: 50 }),
	firstOrderDate: timestamp("first_order_date", { mode: 'string' }),
	lastOrderDate: timestamp("last_order_date", { mode: 'string' }),
	totalOrders: integer("total_orders").default(0),
	totalSpent: numeric("total_spent", { precision: 12, scale:  2 }).default('0'),
	averageOrderValue: numeric("average_order_value", { precision: 12, scale:  2 }).default('0'),
	customerRank: varchar("customer_rank", { length: 20 }),
	lastContactDate: timestamp("last_contact_date", { mode: 'string' }),
	preferredLanguage: varchar("preferred_language", { length: 10 }).default('cs'),
	billingFirstName: varchar("billing_first_name"),
	billingLastName: varchar("billing_last_name"),
	billingCompany: varchar("billing_company"),
	billingEmail: varchar("billing_email"),
	billingTel: varchar("billing_tel"),
	billingStreet: varchar("billing_street"),
	billingStreetNumber: varchar("billing_street_number"),
	billingCity: varchar("billing_city"),
	billingZipCode: varchar("billing_zip_code"),
	billingCountry: varchar("billing_country"),
	ico: varchar(),
	dic: varchar(),
	vatNumber: varchar("vat_number"),
	vatValid: boolean("vat_valid"),
	vatCheckedAt: timestamp("vat_checked_at", { mode: 'string' }),
	vatCompanyName: varchar("vat_company_name"),
	vatCompanyAddress: text("vat_company_address"),
	facebookUrl: varchar("facebook_url"),
	profilePictureUrl: varchar("profile_picture_url"),
	preferredCurrency: varchar("preferred_currency").default('EUR'),
	storeCredit: numeric("store_credit", { precision: 10, scale:  2 }).default('0'),
	isBlacklisted: boolean("is_blacklisted").default(false),
	blacklistedAt: timestamp("blacklisted_at", { mode: 'string' }),
	blacklistReason: text("blacklist_reason"),
	isNew: boolean("is_new").default(true),
});

export const expenses = pgTable("expenses", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	expenseId: varchar("expense_id", { length: 100 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	category: varchar({ length: 100 }),
	amount: numeric({ precision: 12, scale:  2 }).notNull(),
	currency: currency().notNull(),
	paymentMethod: varchar("payment_method", { length: 100 }),
	status: expenseStatus().default('pending'),
	date: timestamp({ mode: 'string' }).notNull(),
	description: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	invoiceNumber: varchar("invoice_number"),
	notes: text(),
	isRecurring: boolean("is_recurring").default(false),
	recurringType: varchar("recurring_type"),
	recurringInterval: integer("recurring_interval").default(1),
	recurringDayOfWeek: integer("recurring_day_of_week"),
	recurringDayOfMonth: integer("recurring_day_of_month"),
	recurringMonth: integer("recurring_month"),
	recurringDay: integer("recurring_day"),
	recurringStartDate: timestamp("recurring_start_date", { mode: 'string' }),
	recurringEndDate: timestamp("recurring_end_date", { mode: 'string' }),
	parentExpenseId: varchar("parent_expense_id"),
});

export const discounts = pgTable("discounts", {
	id: serial().primaryKey().notNull(),
	discountId: text("discount_id").notNull(),
	name: text().notNull(),
	type: text().notNull(),
	percentage: numeric({ precision: 5, scale:  2 }),
	value: numeric({ precision: 10, scale:  2 }),
	minOrderAmount: numeric("min_order_amount", { precision: 10, scale:  2 }),
	status: text().default('active'),
	startDate: date("start_date"),
	endDate: date("end_date"),
	applicationScope: text("application_scope").default('order'),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	buyQuantity: integer("buy_quantity"),
	getQuantity: integer("get_quantity"),
});

export const customerShippingAddresses = pgTable("customer_shipping_addresses", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	customerId: varchar("customer_id").notNull(),
	firstName: varchar("first_name").notNull(),
	lastName: varchar("last_name").notNull(),
	company: varchar(),
	email: varchar(),
	tel: varchar(),
	street: varchar().notNull(),
	streetNumber: varchar("street_number"),
	city: varchar().notNull(),
	zipCode: varchar("zip_code").notNull(),
	country: varchar().notNull(),
	isPrimary: boolean("is_primary").default(false),
	label: varchar(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const landedCosts = pgTable("landed_costs", {
	id: serial().primaryKey().notNull(),
	receiptId: integer("receipt_id").notNull(),
	calculationMethod: text("calculation_method").notNull(),
	baseCost: numeric("base_cost", { precision: 10, scale:  2 }).notNull(),
	shippingCost: numeric("shipping_cost", { precision: 10, scale:  2 }).notNull(),
	customsDuty: numeric("customs_duty", { precision: 10, scale:  2 }).default('0'),
	taxes: numeric({ precision: 10, scale:  2 }).default('0'),
	handlingFees: numeric("handling_fees", { precision: 10, scale:  2 }).default('0'),
	insuranceCost: numeric("insurance_cost", { precision: 10, scale:  2 }).default('0'),
	totalLandedCost: numeric("total_landed_cost", { precision: 10, scale:  2 }).notNull(),
	currency: text().default('USD').notNull(),
	exchangeRates: jsonb("exchange_rates"),
	notes: text(),
	approvedBy: text("approved_by"),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const layoutBins = pgTable("layout_bins", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	layoutId: varchar("layout_id").notNull(),
	code: text().notNull(),
	row: text().notNull(),
	column: integer().notNull(),
	x: numeric({ precision: 10, scale:  2 }).notNull(),
	y: numeric({ precision: 10, scale:  2 }).notNull(),
	width: numeric({ precision: 10, scale:  2 }).notNull(),
	height: numeric({ precision: 10, scale:  2 }).notNull(),
	capacity: integer().default(100).notNull(),
	type: text().default('standard').notNull(),
	status: text().default('active').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const packingCartons = pgTable("packing_cartons", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar().notNull(),
	innerLengthCm: numeric("inner_length_cm", { precision: 10, scale:  2 }).notNull(),
	innerWidthCm: numeric("inner_width_cm", { precision: 10, scale:  2 }).notNull(),
	innerHeightCm: numeric("inner_height_cm", { precision: 10, scale:  2 }).notNull(),
	maxWeightKg: numeric("max_weight_kg", { precision: 10, scale:  2 }).notNull(),
	tareWeightKg: numeric("tare_weight_kg", { precision: 10, scale:  2 }).notNull(),
	carrierCode: varchar("carrier_code"),
	costCurrency: varchar("cost_currency"),
	costAmount: numeric("cost_amount", { precision: 10, scale:  2 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	usageCount: integer("usage_count").default(0).notNull(),
	lastUsedAt: timestamp("last_used_at", { mode: 'string' }),
});

export const orderCartons = pgTable("order_cartons", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	cartonNumber: integer("carton_number").notNull(),
	cartonType: varchar("carton_type").notNull(),
	cartonId: varchar("carton_id"),
	weight: numeric({ precision: 10, scale:  3 }),
	labelUrl: text("label_url"),
	labelPrinted: boolean("label_printed").default(false),
	trackingNumber: text("tracking_number"),
	aiWeightCalculation: jsonb("ai_weight_calculation"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	payloadWeightKg: numeric("payload_weight_kg", { precision: 10, scale:  3 }),
	innerLengthCm: numeric("inner_length_cm", { precision: 10, scale:  2 }),
	innerWidthCm: numeric("inner_width_cm", { precision: 10, scale:  2 }),
	innerHeightCm: numeric("inner_height_cm", { precision: 10, scale:  2 }),
	aiPlanId: varchar("ai_plan_id"),
	source: varchar().default('manual'),
	itemAllocations: jsonb("item_allocations"),
	volumeUtilization: numeric("volume_utilization", { precision: 5, scale:  2 }),
});

export const orderFiles = pgTable("order_files", {
	id: text().primaryKey().notNull(),
	orderId: text("order_id"),
	fileName: text("file_name").notNull(),
	fileUrl: text("file_url").notNull(),
	fileSize: integer("file_size"),
	mimeType: text("mime_type"),
	uploadedBy: text("uploaded_by"),
	uploadedAt: timestamp("uploaded_at", { mode: 'string' }).notNull(),
	isActive: boolean("is_active").default(true),
});

export const orderFulfillmentLogs = pgTable("order_fulfillment_logs", {
	id: serial().primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	userId: varchar("user_id").notNull(),
	activityType: varchar("activity_type").notNull(),
	startedAt: timestamp("started_at", { mode: 'string' }).notNull(),
	completedAt: timestamp("completed_at", { mode: 'string' }),
	itemCount: integer("item_count").default(0).notNull(),
	totalQuantity: integer("total_quantity").default(0).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const orders = pgTable("orders", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id", { length: 50 }).notNull(),
	customerId: varchar("customer_id"),
	billerId: varchar("biller_id"),
	currency: currency().notNull(),
	orderStatus: orderStatus("order_status").default('pending'),
	paymentStatus: paymentStatus("payment_status").default('pending'),
	priority: orderPriority().default('medium'),
	subtotal: numeric({ precision: 12, scale:  2 }).default('0'),
	discountType: discountType("discount_type"),
	discountValue: numeric("discount_value", { precision: 12, scale:  2 }).default('0'),
	taxRate: numeric("tax_rate", { precision: 5, scale:  2 }).default('0'),
	taxAmount: numeric("tax_amount", { precision: 12, scale:  2 }).default('0'),
	shippingMethod: text("shipping_method"),
	paymentMethod: paymentMethod("payment_method"),
	shippingCost: numeric("shipping_cost", { precision: 12, scale:  2 }).default('0'),
	actualShippingCost: numeric("actual_shipping_cost", { precision: 12, scale:  2 }).default('0'),
	grandTotal: numeric("grand_total", { precision: 12, scale:  2 }).notNull(),
	notes: text(),
	attachmentUrl: varchar("attachment_url", { length: 500 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	shippedAt: timestamp("shipped_at", { mode: 'string' }),
	pickStatus: varchar("pick_status", { length: 50 }).default('not_started'),
	packStatus: varchar("pack_status", { length: 50 }).default('not_started'),
	pickedBy: varchar("picked_by", { length: 255 }),
	packedBy: varchar("packed_by", { length: 255 }),
	pickStartTime: timestamp("pick_start_time", { mode: 'string' }),
	pickEndTime: timestamp("pick_end_time", { mode: 'string' }),
	packStartTime: timestamp("pack_start_time", { mode: 'string' }),
	packEndTime: timestamp("pack_end_time", { mode: 'string' }),
	finalWeight: numeric("final_weight", { precision: 8, scale:  2 }),
	cartonUsed: varchar("carton_used", { length: 100 }),
	modifiedAfterPacking: boolean("modified_after_packing").default(false),
	modificationNotes: text("modification_notes"),
	lastModifiedAt: timestamp("last_modified_at", { mode: 'string' }),
	previousPackStatus: varchar("previous_pack_status", { length: 50 }),
	selectedDocumentIds: text("selected_document_ids").array(),
	trackingNumber: text("tracking_number"),
	orderType: varchar("order_type", { length: 10 }).default('ord'),
	includedDocuments: jsonb("included_documents"),
	fulfillmentStage: varchar("fulfillment_stage"),
	pickingStartedAt: timestamp("picking_started_at", { mode: 'string' }),
	packingStartedAt: timestamp("packing_started_at", { mode: 'string' }),
	shippingAddressId: varchar("shipping_address_id"),
	pplBatchId: text("ppl_batch_id"),
	pplShipmentNumbers: text("ppl_shipment_numbers").array(),
	pplLabelData: jsonb("ppl_label_data"),
	pplStatus: varchar("ppl_status"),
	codAmount: numeric("cod_amount", { precision: 10, scale:  2 }),
	codCurrency: varchar("cod_currency"),
	adjustment: numeric().default('0'),
	pplCancelledShipments: text("ppl_cancelled_shipments").array(),
	tax: numeric().default('0'),
	totalCost: numeric("total_cost").default('0'),
	discount: numeric().default('0'),
	allocated: boolean().default(false),
	saleType: varchar("sale_type").default('retail').notNull(),
}, (table) => [
	foreignKey({
			columns: [table.billerId],
			foreignColumns: [users.id],
			name: "orders_biller_id_users_id_fk"
		}),
]);

export const orderCartonPlans = pgTable("order_carton_plans", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	totalCartons: integer("total_cartons").notNull(),
	totalWeightKg: numeric("total_weight_kg", { precision: 10, scale:  2 }).notNull(),
	totalShippingCost: numeric("total_shipping_cost", { precision: 10, scale:  2 }),
	shippingCurrency: varchar("shipping_currency"),
	aiConfidenceScore: numeric("ai_confidence_score", { precision: 3, scale:  2 }),
	status: varchar().default('draft').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	avgUtilization: numeric("avg_utilization", { precision: 5, scale:  2 }),
	suggestions: jsonb(),
	checksum: varchar(),
});

export const notifications = pgTable("notifications", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").notNull(),
	title: text().notNull(),
	description: text(),
	type: varchar().notNull(),
	isRead: boolean("is_read").default(false).notNull(),
	actionUrl: text("action_url"),
	actionLabel: text("action_label"),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const orderItems = pgTable("order_items", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	productId: varchar("product_id"),
	productName: varchar("product_name", { length: 255 }).notNull(),
	sku: varchar({ length: 100 }),
	quantity: integer().notNull(),
	price: numeric({ precision: 12, scale:  2 }).notNull(),
	discount: numeric({ precision: 12, scale:  2 }).default('0'),
	tax: numeric({ precision: 12, scale:  2 }).default('0'),
	total: numeric({ precision: 12, scale:  2 }).notNull(),
	variantId: varchar("variant_id"),
	unitPrice: numeric("unit_price", { precision: 12, scale:  2 }),
	appliedPrice: numeric("applied_price", { precision: 12, scale:  2 }),
	currency: varchar(),
	customerPriceId: varchar("customer_price_id"),
	pickedQuantity: integer("picked_quantity").default(0),
	packedQuantity: integer("packed_quantity").default(0),
	warehouseLocation: varchar("warehouse_location", { length: 100 }),
	barcode: varchar({ length: 50 }),
	image: varchar({ length: 500 }),
	pickStartTime: timestamp("pick_start_time", { mode: 'string' }),
	pickEndTime: timestamp("pick_end_time", { mode: 'string' }),
	packStartTime: timestamp("pack_start_time", { mode: 'string' }),
	packEndTime: timestamp("pack_end_time", { mode: 'string' }),
	serviceId: varchar("service_id"),
	bundleId: varchar("bundle_id"),
	notes: text(),
	landingCost: numeric("landing_cost", { precision: 10, scale:  4 }),
	variantName: varchar("variant_name", { length: 255 }),
	appliedDiscountId: integer("applied_discount_id"),
	appliedDiscountLabel: varchar("applied_discount_label"),
	appliedDiscountType: varchar("applied_discount_type"),
	appliedDiscountScope: varchar("applied_discount_scope"),
	freeItemsCount: integer("free_items_count"),
}, (table) => [
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "order_items_order_id_orders_id_fk"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "order_items_product_id_products_id_fk"
		}),
]);

export const pmSuppliers = pgTable("pm_suppliers", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: text().notNull(),
	contactPerson: text("contact_person"),
	email: text(),
	phone: text(),
	address: text(),
	website: text(),
	notes: text(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const preOrders = pgTable("pre_orders", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	customerId: varchar("customer_id").notNull(),
	status: varchar().default('pending').notNull(),
	notes: text(),
	expectedDate: date("expected_date"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	reminderEnabled: boolean("reminder_enabled").default(false).notNull(),
	reminderChannel: varchar("reminder_channel").default('sms'),
	reminderDaysBefore: integer("reminder_days_before").array().default([RAY[1, ]),
	reminderTimeUtc: varchar("reminder_time_utc").default('09:00'),
	reminderTimezone: varchar("reminder_timezone").default('Europe/Prague'),
	lastReminderSentAt: timestamp("last_reminder_sent_at", { mode: 'string' }),
	lastReminderStatus: varchar("last_reminder_status"),
	reminderPhone: varchar("reminder_phone"),
	reminderEmail: varchar("reminder_email"),
	priority: varchar().default('normal'),
});

export const preOrderReminders = pgTable("pre_order_reminders", {
	id: serial().primaryKey().notNull(),
	preOrderId: varchar("pre_order_id").notNull(),
	channel: varchar().notNull(),
	scheduledFor: timestamp("scheduled_for", { mode: 'string' }).notNull(),
	sentAt: timestamp("sent_at", { mode: 'string' }),
	status: varchar().default('pending').notNull(),
	errorMessage: text("error_message"),
	recipientPhone: varchar("recipient_phone"),
	recipientEmail: varchar("recipient_email"),
	messageContent: text("message_content"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const productCostHistory = pgTable("product_cost_history", {
	id: serial().primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	customItemId: integer("custom_item_id"),
	landingCostUnitBase: numeric("landing_cost_unit_base", { precision: 12, scale:  4 }).notNull(),
	method: text().notNull(),
	computedAt: timestamp("computed_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const permissions = pgTable("permissions", {
	id: serial().primaryKey().notNull(),
	section: varchar({ length: 50 }).notNull(),
	page: varchar({ length: 50 }).notNull(),
	path: varchar({ length: 255 }).notNull(),
	displayName: varchar("display_name", { length: 100 }).notNull(),
	displayNameVi: varchar("display_name_vi", { length: 100 }),
	description: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	parentSection: varchar("parent_section", { length: 50 }).default('warehouse_operations').notNull(),
	isSensitive: boolean("is_sensitive").default(false).notNull(),
});

export const packingMaterials = pgTable("packing_materials", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: text().notNull(),
	code: varchar().notNull(),
	category: varchar().notNull(),
	type: varchar().notNull(),
	size: varchar(),
	dimensions: text(),
	weight: text(),
	stockQuantity: integer("stock_quantity").default(0).notNull(),
	minStockLevel: integer("min_stock_level").default(10).notNull(),
	cost: text(),
	currency: varchar().default('EUR'),
	supplier: text(),
	imageUrl: text("image_url"),
	description: text(),
	isFragile: boolean("is_fragile").default(false),
	isReusable: boolean("is_reusable").default(false),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	nameVi: text("name_vi"),
});

export const preOrderItems = pgTable("pre_order_items", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	preOrderId: varchar("pre_order_id").notNull(),
	productId: varchar("product_id"),
	itemName: varchar("item_name").notNull(),
	itemDescription: text("item_description"),
	quantity: integer().notNull(),
	arrivedQuantity: integer("arrived_quantity").default(0).notNull(),
	purchaseItemId: integer("purchase_item_id"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const productFiles = pgTable("product_files", {
	id: text().primaryKey().notNull(),
	productId: text("product_id"),
	fileName: text("file_name").notNull(),
	fileType: text("file_type").notNull(),
	fileUrl: text("file_url").notNull(),
	fileSize: integer("file_size"),
	mimeType: text("mime_type"),
	description: text(),
	uploadedBy: text("uploaded_by"),
	uploadedAt: timestamp("uploaded_at", { mode: 'string' }).defaultNow().notNull(),
	isActive: boolean("is_active").default(true),
	tags: text().array(),
	language: text(),
});

export const productLocations = pgTable("product_locations", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	locationType: text("location_type").default('warehouse').notNull(),
	locationCode: varchar("location_code").notNull(),
	quantity: integer().default(0).notNull(),
	isPrimary: boolean("is_primary").default(false),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const productTieredPricing = pgTable("product_tiered_pricing", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	minQuantity: integer("min_quantity").notNull(),
	maxQuantity: integer("max_quantity"),
	priceCzk: numeric("price_czk", { precision: 10, scale:  2 }),
	priceEur: numeric("price_eur", { precision: 10, scale:  2 }),
	priceUsd: numeric("price_usd", { precision: 10, scale:  2 }),
	priceVnd: numeric("price_vnd", { precision: 10, scale:  2 }),
	priceCny: numeric("price_cny", { precision: 10, scale:  2 }),
	priceType: varchar("price_type").default('tiered').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
});

export const pushSubscriptions = pgTable("push_subscriptions", {
	id: serial().primaryKey().notNull(),
	userId: varchar("user_id").notNull(),
	endpoint: text().notNull(),
	p256Dh: text().notNull(),
	auth: text().notNull(),
	userAgent: text("user_agent"),
	notificationTypes: text("notification_types").array().default(["RAY['new_order'::tex"]).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	lastUsedAt: timestamp("last_used_at", { mode: 'string' }),
});

export const receipts = pgTable("receipts", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id").notNull(),
	consolidationId: integer("consolidation_id"),
	receivedBy: text("received_by").notNull(),
	receivedAt: timestamp("received_at", { mode: 'string' }).defaultNow().notNull(),
	parcelCount: integer("parcel_count").notNull(),
	carrier: text().notNull(),
	trackingNumbers: jsonb("tracking_numbers"),
	status: text().default('pending_verification').notNull(),
	notes: text(),
	damageNotes: text("damage_notes"),
	photos: jsonb(),
	verifiedBy: text("verified_by"),
	verifiedAt: timestamp("verified_at", { mode: 'string' }),
	approvedBy: text("approved_by"),
	approvedAt: timestamp("approved_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	receivedParcels: integer("received_parcels").default(0).notNull(),
});

export const productVariants = pgTable("product_variants", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	name: varchar({ length: 255 }).notNull(),
	quantity: integer().default(0),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	barcode: varchar({ length: 50 }),
	importCostUsd: numeric("import_cost_usd", { precision: 12, scale:  2 }),
	importCostCzk: numeric("import_cost_czk", { precision: 12, scale:  2 }),
	importCostEur: numeric("import_cost_eur", { precision: 12, scale:  2 }),
	imageUrl: varchar("image_url"),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "product_variants_product_id_products_id_fk"
		}).onDelete("cascade"),
]);

export const receiptItems = pgTable("receipt_items", {
	id: serial().primaryKey().notNull(),
	receiptId: integer("receipt_id").notNull(),
	itemId: integer("item_id").notNull(),
	itemType: text("item_type").notNull(),
	expectedQuantity: integer("expected_quantity").notNull(),
	receivedQuantity: integer("received_quantity").notNull(),
	damagedQuantity: integer("damaged_quantity").default(0),
	missingQuantity: integer("missing_quantity").default(0),
	barcode: text(),
	warehouseLocation: text("warehouse_location"),
	additionalLocation: text("additional_location"),
	storageInstructions: text("storage_instructions"),
	condition: text().default('good'),
	notes: text(),
	photos: jsonb(),
	verifiedAt: timestamp("verified_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	productId: text("product_id"),
	sku: text(),
	status: text().default('ok'),
});

export const productDiscounts = pgTable("product_discounts", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	productId: varchar("product_id").notNull(),
	discountId: integer("discount_id").notNull(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const products = pgTable("products", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar({ length: 255 }).notNull(),
	vietnameseName: varchar("vietnamese_name", { length: 255 }),
	sku: varchar({ length: 100 }).notNull(),
	categoryId: varchar("category_id"),
	warehouseId: varchar("warehouse_id"),
	supplierId: varchar("supplier_id"),
	description: text(),
	quantity: integer().default(0),
	lowStockAlert: integer("low_stock_alert").default(45),
	priceCzk: numeric("price_czk", { precision: 12, scale:  2 }),
	priceEur: numeric("price_eur", { precision: 12, scale:  2 }),
	importCostUsd: numeric("import_cost_usd", { precision: 12, scale:  2 }),
	importCostCzk: numeric("import_cost_czk", { precision: 12, scale:  2 }),
	importCostEur: numeric("import_cost_eur", { precision: 12, scale:  2 }),
	imageUrl: varchar("image_url", { length: 500 }),
	barcode: varchar({ length: 50 }),
	length: numeric({ precision: 10, scale:  2 }),
	width: numeric({ precision: 10, scale:  2 }),
	height: numeric({ precision: 10, scale:  2 }),
	weight: numeric({ precision: 10, scale:  3 }),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow(),
	warehouseLocation: varchar("warehouse_location", { length: 100 }),
	shipmentNotes: text("shipment_notes"),
	packingMaterialId: varchar("packing_material_id"),
	packingInstructionsText: text("packing_instructions_text"),
	packingInstructionsImage: text("packing_instructions_image"),
	latestLandingCost: numeric("latest_landing_cost", { precision: 12, scale:  4 }),
	priceUsd: numeric("price_usd"),
	priceVnd: numeric("price_vnd"),
	priceCny: numeric("price_cny"),
	unitWeightKg: numeric("unit_weight_kg", { precision: 10, scale:  3 }),
	unitLengthCm: numeric("unit_length_cm", { precision: 10, scale:  2 }),
	unitWidthCm: numeric("unit_width_cm", { precision: 10, scale:  2 }),
	unitHeightCm: numeric("unit_height_cm", { precision: 10, scale:  2 }),
	images: jsonb(),
	packingInstructionsImages: jsonb("packing_instructions_images"),
	packingInstructionsTexts: jsonb("packing_instructions_texts"),
	packingMaterials: jsonb("packing_materials"),
	packagingRequirement: text("packaging_requirement").default('carton'),
	reorderRate: integer("reorder_rate"),
	minStockLevel: integer("min_stock_level"),
	maxStockLevel: integer("max_stock_level"),
	lastSoldAt: timestamp("last_sold_at", { mode: 'string' }),
	allocated: boolean().default(false),
	landingCostEur: numeric("landing_cost_eur", { precision: 12, scale:  4 }),
	landingCostUsd: numeric("landing_cost_usd", { precision: 12, scale:  4 }),
	landingCostVnd: numeric("landing_cost_vnd", { precision: 12, scale:  4 }),
	landingCostCzk: numeric("landing_cost_czk", { precision: 12, scale:  4 }),
	landingCostCny: numeric("landing_cost_cny", { precision: 12, scale:  4 }),
	importCostVnd: numeric("import_cost_vnd"),
	importCostCny: numeric("import_cost_cny"),
	sellingUnitName: text("selling_unit_name").default('piece'),
	bulkUnitName: text("bulk_unit_name"),
	bulkUnitQty: integer("bulk_unit_qty"),
	bulkPriceCzk: numeric("bulk_price_czk", { precision: 12, scale:  2 }),
	bulkPriceEur: numeric("bulk_price_eur", { precision: 12, scale:  2 }),
	allowBulkSales: boolean("allow_bulk_sales").default(false),
	unitContentsInfo: text("unit_contents_info"),
	lowStockAlertType: text("low_stock_alert_type").default('percentage'),
	wholesalePriceCzk: numeric("wholesale_price_czk", { precision: 12, scale:  2 }),
	wholesalePriceEur: numeric("wholesale_price_eur", { precision: 12, scale:  2 }),
}, (table) => [
	foreignKey({
			columns: [table.supplierId],
			foreignColumns: [suppliers.id],
			name: "products_supplier_id_suppliers_id_fk"
		}),
]);

export const rolePermissions = pgTable("role_permissions", {
	id: serial().primaryKey().notNull(),
	roleId: integer("role_id").notNull(),
	permissionId: integer("permission_id").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const serviceItems = pgTable("service_items", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	serviceId: varchar("service_id").notNull(),
	productId: varchar("product_id").notNull(),
	productName: varchar("product_name").notNull(),
	sku: varchar(),
	quantity: integer().notNull(),
	unitPrice: numeric("unit_price", { precision: 10, scale:  2 }).notNull(),
	totalPrice: numeric("total_price", { precision: 10, scale:  2 }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipmentItems = pgTable("shipment_items", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id").notNull(),
	consolidationId: integer("consolidation_id").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipmentLabels = pgTable("shipment_labels", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id"),
	carrier: varchar().notNull(),
	trackingNumbers: text("tracking_numbers").array(),
	batchId: varchar("batch_id"),
	labelData: jsonb("label_data"),
	labelBase64: text("label_base64"),
	shipmentCount: integer("shipment_count").default(1),
	status: varchar().default('active').notNull(),
	cancelledAt: timestamp("cancelled_at", { mode: 'string' }),
	cancelReason: text("cancel_reason"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipmentCartons = pgTable("shipment_cartons", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id").notNull(),
	customItemId: integer("custom_item_id").notNull(),
	qtyInCarton: integer("qty_in_carton").notNull(),
	lengthCm: numeric("length_cm", { precision: 10, scale:  2 }),
	widthCm: numeric("width_cm", { precision: 10, scale:  2 }),
	heightCm: numeric("height_cm", { precision: 10, scale:  2 }),
	grossWeightKg: numeric("gross_weight_kg", { precision: 10, scale:  3 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipmentCosts = pgTable("shipment_costs", {
	id: serial().primaryKey().notNull(),
	shipmentId: integer("shipment_id").notNull(),
	type: text().notNull(),
	mode: text(),
	volumetricDivisor: integer("volumetric_divisor"),
	amountOriginal: numeric("amount_original", { precision: 12, scale:  4 }).notNull(),
	currency: text().notNull(),
	fxRateUsed: numeric("fx_rate_used", { precision: 12, scale:  6 }),
	amountBase: numeric("amount_base", { precision: 12, scale:  4 }).notNull(),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipments = pgTable("shipments", {
	id: serial().primaryKey().notNull(),
	consolidationId: integer("consolidation_id"),
	carrier: text().notNull(),
	trackingNumber: text("tracking_number").notNull(),
	origin: text().notNull(),
	destination: text().notNull(),
	status: text().default('dispatched').notNull(),
	shippingCost: numeric("shipping_cost", { precision: 10, scale:  2 }).default('0'),
	insuranceValue: numeric("insurance_value", { precision: 10, scale:  2 }).default('0'),
	estimatedDelivery: timestamp("estimated_delivery", { mode: 'string' }),
	deliveredAt: timestamp("delivered_at", { mode: 'string' }),
	currentLocation: text("current_location"),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	endCarrier: text("end_carrier"),
	endTrackingNumber: text("end_tracking_number"),
	shipmentName: text("shipment_name"),
	shipmentType: text("shipment_type"),
	shippingCostCurrency: text("shipping_cost_currency").default('USD'),
	totalWeight: numeric("total_weight", { precision: 10, scale:  3 }),
	totalUnits: integer("total_units"),
	unitType: text("unit_type").default('items'),
	receivingStatus: text("receiving_status"),
	endTrackingNumbers: text("end_tracking_numbers").array(),
	allocationMethod: text("allocation_method"),
});

export const services = pgTable("services", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	name: varchar().notNull(),
	description: text(),
	status: varchar().default('pending').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	customerId: varchar("customer_id"),
	serviceDate: date("service_date"),
	serviceCost: numeric("service_cost", { precision: 10, scale:  2 }).default('0'),
	partsCost: numeric("parts_cost", { precision: 10, scale:  2 }).default('0'),
	totalCost: numeric("total_cost", { precision: 10, scale:  2 }).default('0'),
	notes: text(),
	currency: varchar().default('EUR'),
	orderId: varchar("order_id"),
});

export const roles = pgTable("roles", {
	id: serial().primaryKey().notNull(),
	name: varchar({ length: 100 }).notNull(),
	displayName: varchar("display_name", { length: 100 }).notNull(),
	displayNameVi: varchar("display_name_vi", { length: 100 }),
	description: text(),
	descriptionVi: text("description_vi"),
	type: varchar({ length: 20 }).default('custom').notNull(),
	isSystem: boolean("is_system").default(false).notNull(),
	color: varchar({ length: 50 }).default('blue'),
	icon: varchar({ length: 50 }).default('Users'),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const shipmentTracking = pgTable("shipment_tracking", {
	id: varchar().default(gen_random_uuid()).primaryKey().notNull(),
	orderId: varchar("order_id").notNull(),
	cartonId: varchar("carton_id"),
	carrier: varchar({ length: 50 }).notNull(),
	trackingNumber: varchar("tracking_number", { length: 100 }).notNull(),
	statusCode: varchar("status_code", { length: 50 }),
	statusLabel: text("status_label"),
	checkpoints: jsonb(),
	estimatedDelivery: timestamp("estimated_delivery", { mode: 'string' }),
	deliveredAt: timestamp("delivered_at", { mode: 'string' }),
	lastEventAt: timestamp("last_event_at", { mode: 'string' }),
	lastCheckedAt: timestamp("last_checked_at", { mode: 'string' }),
	errorState: text("error_state"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});
