import { nanoid } from "nanoid";

// Comprehensive mock data with proper relationships
export const comprehensiveMockData = {
  // Categories (5 total)
  categories: [
    {
      id: "cat-electronics",
      name: "Electronics",
      description: "Electronic devices and accessories",
      createdAt: new Date("2025-01-15T10:00:00Z"),
      updatedAt: new Date("2025-01-15T10:00:00Z"),
    },
    {
      id: "cat-fashion",
      name: "Fashion & Apparel",
      description: "Clothing, shoes, and fashion accessories",
      createdAt: new Date("2025-01-15T10:30:00Z"),
      updatedAt: new Date("2025-01-15T10:30:00Z"),
    },
    {
      id: "cat-sports",
      name: "Sports & Outdoor",
      description: "Sports equipment and outdoor gear",
      createdAt: new Date("2025-01-15T11:00:00Z"),
      updatedAt: new Date("2025-01-15T11:00:00Z"),
    },
    {
      id: "cat-home",
      name: "Home & Garden",
      description: "Home improvement and garden supplies",
      createdAt: new Date("2025-01-15T11:30:00Z"),
      updatedAt: new Date("2025-01-15T11:30:00Z"),
    },
    {
      id: "cat-beauty",
      name: "Beauty & Personal Care",
      description: "Cosmetics and personal care products",
      createdAt: new Date("2025-01-15T12:00:00Z"),
      updatedAt: new Date("2025-01-15T12:00:00Z"),
    },
  ],

  // Warehouses (7 total)
  warehouses: [
    {
      id: "wh-prague-main",
      name: "Prague Main Warehouse",
      code: "PRG-001",
      address: "Průmyslová 15",
      city: "Prague",
      zipCode: "110 00",
      country: "Czech Republic",
      contactPerson: "Pavel Novák",
      phone: "+420 224 123 456",
      email: "pavel.novak@warehouse.cz",
      isActive: true,
      capacity: 10000,
      currentOccupancy: 7500,
      createdAt: new Date("2025-01-10T08:00:00Z"),
      updatedAt: new Date("2025-01-10T08:00:00Z"),
    },
    {
      id: "wh-brno-secondary",
      name: "Brno Secondary Hub",
      code: "BRN-002",
      address: "Technická 28",
      city: "Brno",
      zipCode: "616 00",
      country: "Czech Republic",
      contactPerson: "Jana Svobodová",
      phone: "+420 541 234 567",
      email: "jana.svobodova@warehouse.cz",
      isActive: true,
      capacity: 5000,
      currentOccupancy: 3200,
      createdAt: new Date("2025-01-12T09:00:00Z"),
      updatedAt: new Date("2025-01-12T09:00:00Z"),
    },
    {
      id: "wh-berlin-eu",
      name: "Berlin EU Distribution",
      code: "BER-003",
      address: "Industriestraße 42",
      city: "Berlin",
      zipCode: "13409",
      country: "Germany",
      contactPerson: "Hans Mueller",
      phone: "+49 30 12345678",
      email: "hans.mueller@warehouse.de",
      isActive: true,
      capacity: 8000,
      currentOccupancy: 4500,
      createdAt: new Date("2025-01-14T10:00:00Z"),
      updatedAt: new Date("2025-01-14T10:00:00Z"),
    },
    {
      id: "wh-vienna-regional",
      name: "Vienna Regional Center",
      code: "VIE-004",
      address: "Logistikgasse 7",
      city: "Vienna",
      zipCode: "1230",
      country: "Austria",
      contactPerson: "Maria Schmidt",
      phone: "+43 1 9876543",
      email: "maria.schmidt@warehouse.at",
      isActive: true,
      capacity: 6000,
      currentOccupancy: 3800,
      createdAt: new Date("2025-01-16T11:00:00Z"),
      updatedAt: new Date("2025-01-16T11:00:00Z"),
    },
    {
      id: "wh-ostrava-industrial",
      name: "Ostrava Industrial Hub",
      code: "OST-005",
      address: "Průmyslová zóna 12",
      city: "Ostrava",
      zipCode: "700 30",
      country: "Czech Republic",
      contactPerson: "Tomáš Černý",
      phone: "+420 596 789 012",
      email: "tomas.cerny@warehouse.cz",
      isActive: true,
      capacity: 4000,
      currentOccupancy: 2100,
      createdAt: new Date("2025-01-18T12:00:00Z"),
      updatedAt: new Date("2025-01-18T12:00:00Z"),
    },
    {
      id: "wh-bratislava-sk",
      name: "Bratislava Slovakia Hub",
      code: "BTS-006",
      address: "Skladová 33",
      city: "Bratislava",
      zipCode: "821 04",
      country: "Slovakia",
      contactPerson: "Peter Kováč",
      phone: "+421 2 5555 1234",
      email: "peter.kovac@warehouse.sk",
      isActive: true,
      capacity: 3500,
      currentOccupancy: 2800,
      createdAt: new Date("2025-01-20T13:00:00Z"),
      updatedAt: new Date("2025-01-20T13:00:00Z"),
    },
    {
      id: "wh-plzen-west",
      name: "Plzeň Western Depot",
      code: "PLZ-007",
      address: "Západní 88",
      city: "Plzeň",
      zipCode: "301 00",
      country: "Czech Republic",
      contactPerson: "Eva Nováková",
      phone: "+420 377 456 789",
      email: "eva.novakova@warehouse.cz",
      isActive: false,
      capacity: 2500,
      currentOccupancy: 0,
      createdAt: new Date("2025-01-22T14:00:00Z"),
      updatedAt: new Date("2025-01-22T14:00:00Z"),
    },
  ],

  // Suppliers (8 total)
  suppliers: [
    {
      id: "sup-apple-cz",
      name: "Apple Czech Republic",
      contactPerson: "Milan Kroupa",
      email: "milan.kroupa@apple.com",
      phone: "+420 225 588 000",
      address: "Karlovo náměstí 10",
      city: "Prague",
      zipCode: "120 00",
      country: "Czech Republic",
      website: "https://www.apple.com/cz",
      paymentTerms: "30 days",
      notes: "Premium electronics supplier",
      isActive: true,
      createdAt: new Date("2024-12-01T10:00:00Z"),
      updatedAt: new Date("2024-12-01T10:00:00Z"),
    },
    {
      id: "sup-samsung-europe",
      name: "Samsung Europe B.V.",
      contactPerson: "Jakub Říha",
      email: "jakub.riha@samsung.com",
      phone: "+420 800 726 786",
      address: "Vyskočilova 1461/2a",
      city: "Prague",
      zipCode: "140 00",
      country: "Czech Republic",
      website: "https://www.samsung.com/cz",
      paymentTerms: "45 days",
      notes: "Electronics and appliances",
      isActive: true,
      createdAt: new Date("2024-12-05T11:00:00Z"),
      updatedAt: new Date("2024-12-05T11:00:00Z"),
    },
    {
      id: "sup-nike-emea",
      name: "Nike EMEA B.V.",
      contactPerson: "Petra Svobodová",
      email: "petra.svobodova@nike.com",
      phone: "+31 20 347 7000",
      address: "Colosseum 1",
      city: "Amsterdam",
      zipCode: "1213 NL",
      country: "Netherlands",
      website: "https://www.nike.com",
      paymentTerms: "60 days",
      notes: "Sports apparel and footwear",
      isActive: true,
      createdAt: new Date("2024-12-10T12:00:00Z"),
      updatedAt: new Date("2024-12-10T12:00:00Z"),
    },
    {
      id: "sup-zara-inditex",
      name: "Zara Inditex Group",
      contactPerson: "Carlos Mendez",
      email: "carlos.mendez@zara.com",
      phone: "+34 981 185 400",
      address: "Edificio Inditex",
      city: "A Coruña",
      zipCode: "15142",
      country: "Spain",
      website: "https://www.zara.com",
      paymentTerms: "30 days",
      notes: "Fast fashion retailer",
      isActive: true,
      createdAt: new Date("2024-12-12T13:00:00Z"),
      updatedAt: new Date("2024-12-12T13:00:00Z"),
    },
    {
      id: "sup-loreal-cz",
      name: "L'Oréal Česká republika",
      contactPerson: "Markéta Horáková",
      email: "marketa.horakova@loreal.com",
      phone: "+420 234 767 111",
      address: "Rohanské nábřeží 678/29",
      city: "Prague",
      zipCode: "186 00",
      country: "Czech Republic",
      website: "https://www.loreal.cz",
      paymentTerms: "45 days",
      notes: "Beauty and cosmetics",
      isActive: true,
      createdAt: new Date("2024-12-15T14:00:00Z"),
      updatedAt: new Date("2024-12-15T14:00:00Z"),
    },
    {
      id: "sup-ikea-cz",
      name: "IKEA Česká republika",
      contactPerson: "Lars Andersson",
      email: "lars.andersson@ikea.com",
      phone: "+420 225 000 111",
      address: "Skandinávská 1",
      city: "Prague",
      zipCode: "155 00",
      country: "Czech Republic",
      website: "https://www.ikea.cz",
      paymentTerms: "30 days",
      notes: "Home furniture and accessories",
      isActive: true,
      createdAt: new Date("2024-12-18T15:00:00Z"),
      updatedAt: new Date("2024-12-18T15:00:00Z"),
    },
    {
      id: "sup-xiaomi-europe",
      name: "Xiaomi Europe",
      contactPerson: "Li Wei",
      email: "li.wei@xiaomi.com",
      phone: "+49 89 2050 7400",
      address: "Maximilianstraße 35",
      city: "Munich",
      zipCode: "80539",
      country: "Germany",
      website: "https://www.mi.com/cz",
      paymentTerms: "30 days",
      notes: "Consumer electronics and smart devices",
      isActive: true,
      createdAt: new Date("2024-12-20T16:00:00Z"),
      updatedAt: new Date("2024-12-20T16:00:00Z"),
    },
    {
      id: "sup-decathlon-cz",
      name: "Decathlon Česká republika",
      contactPerson: "Antoine Dubois",
      email: "antoine.dubois@decathlon.com",
      phone: "+420 800 888 800",
      address: "Aviatická 1017/2",
      city: "Prague",
      zipCode: "161 00",
      country: "Czech Republic",
      website: "https://www.decathlon.cz",
      paymentTerms: "45 days",
      notes: "Sports equipment and outdoor gear",
      isActive: true,
      createdAt: new Date("2024-12-22T17:00:00Z"),
      updatedAt: new Date("2024-12-22T17:00:00Z"),
    },
  ],

  // Products (20 total)
  products: [
    {
      id: "prod-iphone-15-pro",
      name: "iPhone 15 Pro Max",
      sku: "APPLE-IP15PM-256",
      categoryId: "cat-electronics",
      supplierId: "sup-apple-cz",
      warehouseId: "wh-prague-main",
      description: "Latest iPhone with A17 Pro chip, 256GB storage",
      importCost: "28000.00",
      sellingPrice: "32000.00",
      currency: "CZK",
      stockQuantity: 45,
      lowStockThreshold: 10,
      barcode: "194253394051",
      imageUrl: "/images/iphone-15-pro-max.jpg",
      weight: 0.221,
      dimensions: "159.9x76.7x8.25",
      isActive: true,
      createdAt: new Date("2025-01-05T10:00:00Z"),
      updatedAt: new Date("2025-01-05T10:00:00Z"),
    },
    {
      id: "prod-macbook-m3",
      name: "MacBook Pro 16\" M3",
      sku: "APPLE-MBP16-M3-512",
      categoryId: "cat-electronics",
      supplierId: "sup-apple-cz",
      warehouseId: "wh-prague-main",
      description: "MacBook Pro with M3 chip, 16GB RAM, 512GB SSD",
      importCost: "65000.00",
      sellingPrice: "72000.00",
      currency: "CZK",
      stockQuantity: 12,
      lowStockThreshold: 5,
      barcode: "194253564789",
      imageUrl: "/images/macbook-pro-m3.jpg",
      weight: 2.14,
      dimensions: "355.7x248.1x16.8",
      isActive: true,
      createdAt: new Date("2025-01-06T11:00:00Z"),
      updatedAt: new Date("2025-01-06T11:00:00Z"),
    },
    {
      id: "prod-airpods-pro-2",
      name: "AirPods Pro (2nd Gen)",
      sku: "APPLE-APP-2GEN-USB",
      categoryId: "cat-electronics",
      supplierId: "sup-apple-cz",
      warehouseId: "wh-prague-main",
      description: "Active Noise Cancellation, USB-C charging case",
      importCost: "6500.00",
      sellingPrice: "7500.00",
      currency: "CZK",
      stockQuantity: 78,
      lowStockThreshold: 20,
      barcode: "194253506789",
      imageUrl: "/images/airpods-pro-2nd-gen.jpg",
      weight: 0.056,
      dimensions: "6.1x4.5x2.1",
      isActive: true,
      createdAt: new Date("2025-01-07T12:00:00Z"),
      updatedAt: new Date("2025-01-07T12:00:00Z"),
    },
    {
      id: "prod-samsung-s24-ultra",
      name: "Samsung Galaxy S24 Ultra",
      sku: "SAMSUNG-GS24-ULTRA-512",
      categoryId: "cat-electronics",
      supplierId: "sup-samsung-europe",
      warehouseId: "wh-berlin-eu",
      description: "Flagship smartphone with S Pen, 512GB storage",
      importCost: "1050.00",
      sellingPrice: "1249.00",
      currency: "EUR",
      stockQuantity: 32,
      lowStockThreshold: 8,
      barcode: "887276789456",
      imageUrl: "/images/galaxy-s24-ultra.jpg",
      weight: 0.232,
      dimensions: "162.3x79x8.6",
      isActive: true,
      createdAt: new Date("2025-01-08T13:00:00Z"),
      updatedAt: new Date("2025-01-08T13:00:00Z"),
    },
    {
      id: "prod-samsung-qled-tv",
      name: "Samsung 65\" QLED 4K TV",
      sku: "SAMSUNG-QN65Q80C",
      categoryId: "cat-electronics",
      supplierId: "sup-samsung-europe",
      warehouseId: "wh-berlin-eu",
      description: "65-inch QLED 4K Smart TV with HDR10+",
      importCost: "1200.00",
      sellingPrice: "1399.00",
      currency: "EUR",
      stockQuantity: 8,
      lowStockThreshold: 3,
      barcode: "887276345678",
      imageUrl: "/images/samsung-qled-65.jpg",
      weight: 28.5,
      dimensions: "144.6x82.9x5.9",
      isActive: true,
      createdAt: new Date("2025-01-09T14:00:00Z"),
      updatedAt: new Date("2025-01-09T14:00:00Z"),
    },
    {
      id: "prod-nike-air-max",
      name: "Nike Air Max 270",
      sku: "NIKE-AM270-BLK-42",
      categoryId: "cat-sports",
      supplierId: "sup-nike-emea",
      warehouseId: "wh-vienna-regional",
      description: "Men's running shoes, black colorway, size 42",
      importCost: "85.00",
      sellingPrice: "119.99",
      currency: "EUR",
      stockQuantity: 25,
      lowStockThreshold: 5,
      barcode: "194501234567",
      imageUrl: "/images/nike-air-max-270.jpg",
      weight: 0.65,
      dimensions: "32x12x11",
      isActive: true,
      createdAt: new Date("2025-01-10T15:00:00Z"),
      updatedAt: new Date("2025-01-10T15:00:00Z"),
    },
    {
      id: "prod-nike-dri-fit-shirt",
      name: "Nike Dri-FIT Training Shirt",
      sku: "NIKE-DF-TRAIN-L-BLU",
      categoryId: "cat-sports",
      supplierId: "sup-nike-emea",
      warehouseId: "wh-vienna-regional",
      description: "Men's training shirt, moisture-wicking, size L, blue",
      importCost: "18.00",
      sellingPrice: "29.99",
      currency: "EUR",
      stockQuantity: 67,
      lowStockThreshold: 15,
      barcode: "194507654321",
      imageUrl: "/images/nike-dri-fit-shirt.jpg",
      weight: 0.2,
      dimensions: "28x20x2",
      isActive: true,
      createdAt: new Date("2025-01-11T16:00:00Z"),
      updatedAt: new Date("2025-01-11T16:00:00Z"),
    },
    {
      id: "prod-zara-blazer",
      name: "Zara Structured Blazer",
      sku: "ZARA-BLAZER-M-GRY",
      categoryId: "cat-fashion",
      supplierId: "sup-zara-inditex",
      warehouseId: "wh-bratislava-sk",
      description: "Women's structured blazer, medium size, grey",
      importCost: "35.00",
      sellingPrice: "69.95",
      currency: "EUR",
      stockQuantity: 42,
      lowStockThreshold: 10,
      barcode: "843701234567",
      imageUrl: "/images/zara-structured-blazer.jpg",
      weight: 0.45,
      dimensions: "40x30x5",
      isActive: true,
      createdAt: new Date("2025-01-12T17:00:00Z"),
      updatedAt: new Date("2025-01-12T17:00:00Z"),
    },
    {
      id: "prod-zara-jeans",
      name: "Zara High-Waist Straight Jeans",
      sku: "ZARA-JEANS-W30-INDIG",
      categoryId: "cat-fashion",
      supplierId: "sup-zara-inditex",
      warehouseId: "wh-bratislava-sk",
      description: "Women's high-waist straight jeans, W30, indigo",
      importCost: "22.00",
      sellingPrice: "45.95",
      currency: "EUR",
      stockQuantity: 55,
      lowStockThreshold: 12,
      barcode: "843707654321",
      imageUrl: "/images/zara-high-waist-jeans.jpg",
      weight: 0.6,
      dimensions: "35x25x3",
      isActive: true,
      createdAt: new Date("2025-01-13T18:00:00Z"),
      updatedAt: new Date("2025-01-13T18:00:00Z"),
    },
    {
      id: "prod-loreal-foundation",
      name: "L'Oréal True Match Foundation",
      sku: "LOREAL-TM-FOUND-C3",
      categoryId: "cat-beauty",
      supplierId: "sup-loreal-cz",
      warehouseId: "wh-brno-secondary",
      description: "Liquid foundation, shade C3 Rose Beige, 30ml",
      importCost: "320.00",
      sellingPrice: "459.00",
      currency: "CZK",
      stockQuantity: 89,
      lowStockThreshold: 20,
      barcode: "3600523351234",
      imageUrl: "/images/loreal-true-match.jpg",
      weight: 0.08,
      dimensions: "4x4x12",
      isActive: true,
      createdAt: new Date("2025-01-14T19:00:00Z"),
      updatedAt: new Date("2025-01-14T19:00:00Z"),
    },
    {
      id: "prod-loreal-mascara",
      name: "L'Oréal Voluminous Lash Paradise",
      sku: "LOREAL-VLP-MASC-BLK",
      categoryId: "cat-beauty",
      supplierId: "sup-loreal-cz",
      warehouseId: "wh-brno-secondary",
      description: "Volumizing mascara, black, waterproof formula",
      importCost: "250.00",
      sellingPrice: "349.00",
      currency: "CZK",
      stockQuantity: 76,
      lowStockThreshold: 18,
      barcode: "3600523567890",
      imageUrl: "/images/loreal-lash-paradise.jpg",
      weight: 0.025,
      dimensions: "2x2x14",
      isActive: true,
      createdAt: new Date("2025-01-15T20:00:00Z"),
      updatedAt: new Date("2025-01-15T20:00:00Z"),
    },
    {
      id: "prod-ikea-desk",
      name: "IKEA LINNMON Desk",
      sku: "IKEA-LINNMON-120-WHT",
      categoryId: "cat-home",
      supplierId: "sup-ikea-cz",
      warehouseId: "wh-ostrava-industrial",
      description: "Office desk, 120x60cm, white finish",
      importCost: "890.00",
      sellingPrice: "1299.00",
      currency: "CZK",
      stockQuantity: 18,
      lowStockThreshold: 5,
      barcode: "4006581234567",
      imageUrl: "/images/ikea-linnmon-desk.jpg",
      weight: 15.2,
      dimensions: "120x60x4",
      isActive: true,
      createdAt: new Date("2025-01-16T21:00:00Z"),
      updatedAt: new Date("2025-01-16T21:00:00Z"),
    },
    {
      id: "prod-ikea-chair",
      name: "IKEA MARKUS Office Chair",
      sku: "IKEA-MARKUS-GRY-ADJ",
      categoryId: "cat-home",
      supplierId: "sup-ikea-cz",
      warehouseId: "wh-ostrava-industrial",
      description: "Ergonomic office chair, grey, adjustable height",
      importCost: "3200.00",
      sellingPrice: "4599.00",
      currency: "CZK",
      stockQuantity: 14,
      lowStockThreshold: 4,
      barcode: "4006587654321",
      imageUrl: "/images/ikea-markus-chair.jpg",
      weight: 24.8,
      dimensions: "62x60x129",
      isActive: true,
      createdAt: new Date("2025-01-17T22:00:00Z"),
      updatedAt: new Date("2025-01-17T22:00:00Z"),
    },
    {
      id: "prod-xiaomi-phone",
      name: "Xiaomi 14 Pro",
      sku: "XIAOMI-14PRO-512-BLK",
      categoryId: "cat-electronics",
      supplierId: "sup-xiaomi-europe",
      warehouseId: "wh-berlin-eu",
      description: "Flagship smartphone, 512GB, Leica camera, black",
      importCost: "650.00",
      sellingPrice: "899.00",
      currency: "EUR",
      stockQuantity: 28,
      lowStockThreshold: 8,
      barcode: "6934177771234",
      imageUrl: "/images/xiaomi-14-pro.jpg",
      weight: 0.225,
      dimensions: "161.4x74.6x8.2",
      isActive: true,
      createdAt: new Date("2025-01-18T23:00:00Z"),
      updatedAt: new Date("2025-01-18T23:00:00Z"),
    },
    {
      id: "prod-xiaomi-scooter",
      name: "Xiaomi Mi Electric Scooter 4",
      sku: "XIAOMI-SCOOT4-BLK",
      categoryId: "cat-sports",
      supplierId: "sup-xiaomi-europe",
      warehouseId: "wh-berlin-eu",
      description: "Electric scooter, 25km/h max speed, 30km range",
      importCost: "280.00",
      sellingPrice: "399.00",
      currency: "EUR",
      stockQuantity: 15,
      lowStockThreshold: 5,
      barcode: "6934177787654",
      imageUrl: "/images/xiaomi-scooter-4.jpg",
      weight: 14.2,
      dimensions: "108x43x114",
      isActive: true,
      createdAt: new Date("2025-01-19T08:00:00Z"),
      updatedAt: new Date("2025-01-19T08:00:00Z"),
    },
    {
      id: "prod-decathlon-bike",
      name: "Decathlon Riverside 120",
      sku: "DECATH-RIV120-L-BLU",
      categoryId: "cat-sports",
      supplierId: "sup-decathlon-cz",
      warehouseId: "wh-prague-main",
      description: "Hybrid bike, size L, 21-speed, blue color",
      importCost: "4500.00",
      sellingPrice: "6999.00",
      currency: "CZK",
      stockQuantity: 9,
      lowStockThreshold: 3,
      barcode: "3608439001234",
      imageUrl: "/images/decathlon-riverside-120.jpg",
      weight: 13.5,
      dimensions: "180x65x100",
      isActive: true,
      createdAt: new Date("2025-01-20T09:00:00Z"),
      updatedAt: new Date("2025-01-20T09:00:00Z"),
    },
    {
      id: "prod-decathlon-backpack",
      name: "Decathlon Forclaz 50L Backpack",
      sku: "DECATH-FORC50-GRN",
      categoryId: "cat-sports",
      supplierId: "sup-decathlon-cz",
      warehouseId: "wh-prague-main",
      description: "Hiking backpack, 50L capacity, green color",
      importCost: "890.00",
      sellingPrice: "1299.00",
      currency: "CZK",
      stockQuantity: 22,
      lowStockThreshold: 6,
      barcode: "3608439007654",
      imageUrl: "/images/decathlon-backpack-50l.jpg",
      weight: 1.8,
      dimensions: "60x35x25",
      isActive: true,
      createdAt: new Date("2025-01-21T10:00:00Z"),
      updatedAt: new Date("2025-01-21T10:00:00Z"),
    },
    {
      id: "prod-samsung-watch",
      name: "Samsung Galaxy Watch 6",
      sku: "SAMSUNG-GW6-44-SLV",
      categoryId: "cat-electronics",
      supplierId: "sup-samsung-europe",
      warehouseId: "wh-vienna-regional",
      description: "Smartwatch, 44mm, silver aluminum, GPS",
      importCost: "220.00",
      sellingPrice: "329.00",
      currency: "EUR",
      stockQuantity: 38,
      lowStockThreshold: 10,
      barcode: "887276123456",
      imageUrl: "/images/galaxy-watch-6.jpg",
      weight: 0.033,
      dimensions: "4.4x4.4x1.09",
      isActive: true,
      createdAt: new Date("2025-01-22T11:00:00Z"),
      updatedAt: new Date("2025-01-22T11:00:00Z"),
    },
    {
      id: "prod-nike-jacket",
      name: "Nike Sportswear Tech Fleece",
      sku: "NIKE-TECH-FLEECE-XL-BLK",
      categoryId: "cat-sports",
      supplierId: "sup-nike-emea",
      warehouseId: "wh-bratislava-sk",
      description: "Men's full-zip hoodie, size XL, black",
      importCost: "55.00",
      sellingPrice: "89.99",
      currency: "EUR",
      stockQuantity: 41,
      lowStockThreshold: 12,
      barcode: "194502345678",
      imageUrl: "/images/nike-tech-fleece.jpg",
      weight: 0.8,
      dimensions: "35x25x8",
      isActive: true,
      createdAt: new Date("2025-01-23T12:00:00Z"),
      updatedAt: new Date("2025-01-23T12:00:00Z"),
    },
    {
      id: "prod-zara-dress",
      name: "Zara Floral Print Midi Dress",
      sku: "ZARA-DRESS-M-FLOR",
      categoryId: "cat-fashion",
      supplierId: "sup-zara-inditex",
      warehouseId: "wh-vienna-regional",
      description: "Women's midi dress, size M, floral print",
      importCost: "28.00",
      sellingPrice: "59.95",
      currency: "EUR",
      stockQuantity: 33,
      lowStockThreshold: 8,
      barcode: "843708765432",
      imageUrl: "/images/zara-floral-dress.jpg",
      weight: 0.35,
      dimensions: "38x28x3",
      isActive: true,
      createdAt: new Date("2025-01-24T13:00:00Z"),
      updatedAt: new Date("2025-01-24T13:00:00Z"),
    },
  ],

  // Customers (15 total) - Mix of individual and business customers
  customers: [
    {
      id: "cust-pavel-novak",
      name: "Pavel Novák",
      facebookName: "Pavel N.",
      facebookId: "pavel.novak.123",
      email: "pavel.novak@gmail.com",
      phone: "+420 777 123 456",
      address: "Wenceslas Square 14",
      city: "Prague",
      zipCode: "110 00",
      country: "Czech Republic",
      type: "vip" as const,
      notes: "VIP customer - prefers premium products, expedited shipping",
      createdAt: new Date("2024-10-15T10:00:00Z"),
      updatedAt: new Date("2024-10-15T10:00:00Z"),
    },
    {
      id: "cust-anna-svoboda",
      name: "Anna Svobodová",
      facebookName: "Anna Svobodová",
      facebookId: "anna.svoboda.456",
      email: "anna.svoboda@email.cz",
      phone: "+420 603 456 789",
      address: "Národní třída 28",
      city: "Prague",
      zipCode: "110 00",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Fashion enthusiast, frequent online shopper",
      createdAt: new Date("2024-11-02T11:00:00Z"),
      updatedAt: new Date("2024-11-02T11:00:00Z"),
    },
    {
      id: "cust-tech-solutions",
      name: "Tech Solutions s.r.o.",
      facebookName: null,
      facebookId: null,
      email: "orders@techsolutions.cz",
      phone: "+420 234 567 890",
      address: "Palackého třída 123",
      city: "Brno",
      zipCode: "602 00",
      country: "Czech Republic",
      type: "business" as const,
      notes: "B2B customer - bulk orders, 30-day payment terms",
      createdAt: new Date("2024-09-20T12:00:00Z"),
      updatedAt: new Date("2024-09-20T12:00:00Z"),
    },
    {
      id: "cust-maria-schmidt",
      name: "Maria Schmidt",
      facebookName: "Maria S.",
      facebookId: "maria.schmidt.789",
      email: "maria.schmidt@gmail.com",
      phone: "+43 664 123 4567",
      address: "Mariahilfer Straße 88",
      city: "Vienna",
      zipCode: "1070",
      country: "Austria",
      type: "vip" as const,
      notes: "Austrian VIP customer, prefers German communication",
      createdAt: new Date("2024-10-08T13:00:00Z"),
      updatedAt: new Date("2024-10-08T13:00:00Z"),
    },
    {
      id: "cust-jan-dvorak",
      name: "Jan Dvořák",
      facebookName: null,
      facebookId: null,
      email: "jan.dvorak@centrum.cz",
      phone: "+420 721 987 654",
      address: "Americká 15",
      city: "Plzeň",
      zipCode: "301 00",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Electronics enthusiast, prefers weekend delivery",
      createdAt: new Date("2024-11-10T14:00:00Z"),
      updatedAt: new Date("2024-11-10T14:00:00Z"),
    },
    {
      id: "cust-electronics-hub",
      name: "Electronics Hub GmbH",
      facebookName: null,
      facebookId: null,
      email: "purchasing@electronichub.de",
      phone: "+49 30 123 456 78",
      address: "Alexanderplatz 1",
      city: "Berlin",
      zipCode: "10178",
      country: "Germany",
      type: "business" as const,
      notes: "German electronics retailer, large volume orders",
      createdAt: new Date("2024-09-01T15:00:00Z"),
      updatedAt: new Date("2024-09-01T15:00:00Z"),
    },
    {
      id: "cust-petra-horakova",
      name: "Petra Horáková",
      facebookName: "Petra H.",
      facebookId: "petra.horakova.321",
      email: "petra.horakova@seznam.cz",
      phone: "+420 608 321 654",
      address: "Dlouhá 33",
      city: "Prague",
      zipCode: "110 00",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Beauty products enthusiast, active on social media",
      createdAt: new Date("2024-11-15T16:00:00Z"),
      updatedAt: new Date("2024-11-15T16:00:00Z"),
    },
    {
      id: "cust-fitness-first",
      name: "Fitness First Praha",
      facebookName: null,
      facebookId: null,
      email: "procurement@fitnessfirst.cz",
      phone: "+420 222 888 999",
      address: "Václavské náměstí 56",
      city: "Prague",
      zipCode: "110 00",
      country: "Czech Republic",
      type: "business" as const,
      notes: "Gym chain, bulk sports equipment orders",
      createdAt: new Date("2024-08-15T17:00:00Z"),
      updatedAt: new Date("2024-08-15T17:00:00Z"),
    },
    {
      id: "cust-lukas-krejci",
      name: "Lukáš Krejčí",
      facebookName: "Lukáš K.",
      facebookId: "lukas.krejci.654",
      email: "lukas.krejci@email.cz",
      phone: "+420 775 654 321",
      address: "Botanická 68",
      city: "Brno",
      zipCode: "602 00",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Tech-savvy customer, early adopter of new products",
      createdAt: new Date("2024-12-01T18:00:00Z"),
      updatedAt: new Date("2024-12-01T18:00:00Z"),
    },
    {
      id: "cust-fashion-boutique",
      name: "Fashion Boutique Vienna",
      facebookName: null,
      facebookId: null,
      email: "orders@fashionboutique.at",
      phone: "+43 1 555 0123",
      address: "Graben 21",
      city: "Vienna",
      zipCode: "1010",
      country: "Austria",
      type: "business" as const,
      notes: "Boutique fashion retailer, seasonal orders",
      createdAt: new Date("2024-07-20T19:00:00Z"),
      updatedAt: new Date("2024-07-20T19:00:00Z"),
    },
    {
      id: "cust-tomas-cerny",
      name: "Tomáš Černý",
      facebookName: "Tomáš Č.",
      facebookId: "tomas.cerny.987",
      email: "tomas.cerny@gmail.com",
      phone: "+420 736 987 123",
      address: "Ostravská 42",
      city: "Ostrava",
      zipCode: "702 00",
      country: "Czech Republic",
      type: "vip" as const,
      notes: "VIP customer from Ostrava, high-value orders",
      createdAt: new Date("2024-09-10T20:00:00Z"),
      updatedAt: new Date("2024-09-10T20:00:00Z"),
    },
    {
      id: "cust-home-design",
      name: "Home Design Slovakia",
      facebookName: null,
      facebookId: null,
      email: "info@homedesign.sk",
      phone: "+421 2 5555 4444",
      address: "Hlavné námestie 12",
      city: "Bratislava",
      zipCode: "811 01",
      country: "Slovakia",
      type: "business" as const,
      notes: "Interior design company, furniture and home goods",
      createdAt: new Date("2024-06-25T21:00:00Z"),
      updatedAt: new Date("2024-06-25T21:00:00Z"),
    },
    {
      id: "cust-eva-novakova",
      name: "Eva Nováková",
      facebookName: "Eva N.",
      facebookId: "eva.novakova.147",
      email: "eva.novakova@email.cz",
      phone: "+420 607 147 258",
      address: "Jiráskova 89",
      city: "České Budějovice",
      zipCode: "370 01",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Loyal customer, family purchases, environmentally conscious",
      createdAt: new Date("2024-10-30T22:00:00Z"),
      updatedAt: new Date("2024-10-30T22:00:00Z"),
    },
    {
      id: "cust-sport-shop",
      name: "Sport Shop Berlin",
      facebookName: null,
      facebookId: null,
      email: "bestellung@sportshop-berlin.de",
      phone: "+49 30 987 654 32",
      address: "Unter den Linden 77",
      city: "Berlin",
      zipCode: "10117",
      country: "Germany",
      type: "business" as const,
      notes: "Sports equipment retailer, regular wholesale orders",
      createdAt: new Date("2024-05-15T23:00:00Z"),
      updatedAt: new Date("2024-05-15T23:00:00Z"),
    },
    {
      id: "cust-karel-svoboda",
      name: "Karel Svoboda",
      facebookName: "Karel S.",
      facebookId: "karel.svoboda.369",
      email: "karel.svoboda@centrum.cz",
      phone: "+420 704 369 852",
      address: "Pražská 156",
      city: "Hradec Králové",
      zipCode: "500 02",
      country: "Czech Republic",
      type: "regular" as const,
      notes: "Outdoor enthusiast, camping and hiking gear",
      createdAt: new Date("2024-12-10T08:00:00Z"),
      updatedAt: new Date("2024-12-10T08:00:00Z"),
    },
  ],
};