import { db } from './db';
import { packingMaterials } from '../shared/schema';

export async function seedPackingMaterials() {
  console.log('Seeding packing materials...');

  const materials = [
    // Cartons & Boxes
    {
      name: 'Small Shipping Carton',
      code: 'CTN-SM-001',
      category: 'cartons',
      type: 'small_carton',
      size: 's',
      dimensions: '20x15x10 cm',
      weight: '150g',
      stockQuantity: 500,
      minStockLevel: 100,
      cost: '0.45',
      currency: 'EUR',
      supplier: 'PackPro Supplies',
      description: 'Ideal for small beauty product shipments',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Medium Shipping Carton',
      code: 'CTN-MD-001',
      category: 'cartons',
      type: 'medium_carton',
      size: 'm',
      dimensions: '30x25x20 cm',
      weight: '280g',
      stockQuantity: 400,
      minStockLevel: 80,
      cost: '0.75',
      currency: 'EUR',
      supplier: 'PackPro Supplies',
      description: 'Perfect for standard nail salon orders',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Large Shipping Carton',
      code: 'CTN-LG-001',
      category: 'cartons',
      type: 'large_carton',
      size: 'l',
      dimensions: '40x35x30 cm',
      weight: '420g',
      stockQuantity: 300,
      minStockLevel: 60,
      cost: '1.20',
      currency: 'EUR',
      supplier: 'PackPro Supplies',
      description: 'For bulk nail product shipments',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Premium Gift Box',
      code: 'GFT-BX-001',
      category: 'cartons',
      type: 'gift_box',
      size: 'm',
      dimensions: '25x20x10 cm',
      weight: '180g',
      stockQuantity: 150,
      minStockLevel: 30,
      cost: '1.80',
      currency: 'EUR',
      supplier: 'Luxury Pack Solutions',
      description: 'Elegant gift packaging for premium nail sets',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },

    // Filling Materials
    {
      name: 'Bubble Wrap Roll',
      code: 'BWP-RL-001',
      category: 'filling',
      type: 'bubble_wrap',
      size: 'l',
      dimensions: '100m x 50cm',
      weight: '2.5kg',
      stockQuantity: 80,
      minStockLevel: 15,
      cost: '12.50',
      currency: 'EUR',
      supplier: 'Protective Pack Co',
      description: 'Heavy-duty bubble wrap for fragile items',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Air Cushion Pillows',
      code: 'ACP-001',
      category: 'filling',
      type: 'air_pillows',
      size: 'm',
      dimensions: '20x10 cm (inflated)',
      weight: '5g each',
      stockQuantity: 5000,
      minStockLevel: 1000,
      cost: '0.02',
      currency: 'EUR',
      supplier: 'EcoPack Systems',
      description: 'Eco-friendly void fill air cushions',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Foam Corner Protectors',
      code: 'FCP-001',
      category: 'filling',
      type: 'foam_corners',
      size: 'm',
      dimensions: '5x5x30 cm',
      weight: '25g',
      stockQuantity: 800,
      minStockLevel: 150,
      cost: '0.15',
      currency: 'EUR',
      supplier: 'Protective Pack Co',
      description: 'L-shaped foam protectors for carton edges',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Kraft Paper Fill',
      code: 'KPF-001',
      category: 'filling',
      type: 'paper_fill',
      size: 'l',
      dimensions: 'Shredded',
      weight: '10kg per bag',
      stockQuantity: 40,
      minStockLevel: 10,
      cost: '8.90',
      currency: 'EUR',
      supplier: 'EcoPack Systems',
      description: 'Eco-friendly kraft paper void fill',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },

    // Pallets & Platforms
    {
      name: 'Euro Pallet',
      code: 'PLT-EUR-001',
      category: 'pallets',
      type: 'euro_pallet',
      size: 'xl',
      dimensions: '120x80x14.4 cm',
      weight: '25kg',
      stockQuantity: 50,
      minStockLevel: 10,
      cost: '12.00',
      currency: 'EUR',
      supplier: 'Euro Logistics',
      description: 'Standard EUR-EPAL certified wooden pallet',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Half Euro Pallet',
      code: 'PLT-HLF-001',
      category: 'pallets',
      type: 'half_pallet',
      size: 'l',
      dimensions: '60x80x14.4 cm',
      weight: '12kg',
      stockQuantity: 30,
      minStockLevel: 8,
      cost: '7.50',
      currency: 'EUR',
      supplier: 'Euro Logistics',
      description: 'Half-size pallet for smaller shipments',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },

    // Protective Materials
    {
      name: 'Stretch Film Industrial Roll',
      code: 'STF-IND-001',
      category: 'protective',
      type: 'stretch_film',
      size: 'xl',
      dimensions: '500mm x 300m',
      weight: '3.2kg',
      stockQuantity: 60,
      minStockLevel: 12,
      cost: '18.50',
      currency: 'EUR',
      supplier: 'Wrap Masters',
      description: 'Heavy-duty stretch wrap for pallet securing',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Packing Tape Premium',
      code: 'TPE-PRE-001',
      category: 'protective',
      type: 'packing_tape',
      size: 'm',
      dimensions: '48mm x 66m',
      weight: '180g',
      stockQuantity: 500,
      minStockLevel: 100,
      cost: '0.95',
      currency: 'EUR',
      supplier: 'TapeWorld Pro',
      description: 'High-tack acrylic adhesive tape',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Fragile Warning Tape',
      code: 'TPE-FRG-001',
      category: 'protective',
      type: 'fragile_tape',
      size: 'm',
      dimensions: '48mm x 66m',
      weight: '180g',
      stockQuantity: 200,
      minStockLevel: 40,
      cost: '1.20',
      currency: 'EUR',
      supplier: 'TapeWorld Pro',
      description: 'Red FRAGILE printed warning tape',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Edge Protector Cardboard',
      code: 'EPR-CDB-001',
      category: 'protective',
      type: 'edge_protectors',
      size: 'l',
      dimensions: '5x5x100 cm',
      weight: '120g',
      stockQuantity: 300,
      minStockLevel: 60,
      cost: '0.35',
      currency: 'EUR',
      supplier: 'Protective Pack Co',
      description: 'L-angle cardboard edge protectors',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },

    // Packing Tools
    {
      name: 'Heavy-Duty Tape Dispenser',
      code: 'DSP-TPE-001',
      category: 'tools',
      type: 'tape_dispenser',
      size: 'm',
      dimensions: '15x10x5 cm',
      weight: '280g',
      stockQuantity: 25,
      minStockLevel: 5,
      cost: '8.50',
      currency: 'EUR',
      supplier: 'Warehouse Tools Inc',
      description: 'Ergonomic tape gun for 48mm tape',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Safety Box Cutter',
      code: 'CUT-SAF-001',
      category: 'tools',
      type: 'box_cutter',
      size: 's',
      dimensions: '15cm length',
      weight: '85g',
      stockQuantity: 40,
      minStockLevel: 10,
      cost: '3.20',
      currency: 'EUR',
      supplier: 'Warehouse Tools Inc',
      description: 'Retractable safety blade cutter',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Stretch Wrap Dispenser',
      code: 'DSP-STR-001',
      category: 'tools',
      type: 'stretch_wrap_dispenser',
      size: 'l',
      dimensions: '50cm handle',
      weight: '1.2kg',
      stockQuantity: 15,
      minStockLevel: 3,
      cost: '28.00',
      currency: 'EUR',
      supplier: 'Wrap Masters',
      description: 'Professional pallet wrap applicator',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Digital Packing Scale',
      code: 'SCL-DIG-001',
      category: 'tools',
      type: 'scale',
      size: 'l',
      dimensions: '30x30x5 cm platform',
      weight: '2.5kg',
      stockQuantity: 8,
      minStockLevel: 2,
      cost: '45.00',
      currency: 'EUR',
      supplier: 'WeighTech Pro',
      description: '50kg capacity digital scale',
      isFragile: true,
      isReusable: true,
      isActive: true,
    },

    // General Supplies
    {
      name: 'Thermal Shipping Labels',
      code: 'LBL-THM-001',
      category: 'supplies',
      type: 'shipping_labels',
      size: 'm',
      dimensions: '10x15 cm',
      weight: '500g per roll',
      stockQuantity: 200,
      minStockLevel: 40,
      cost: '12.50',
      currency: 'EUR',
      supplier: 'Label Solutions Pro',
      description: '1000 labels per roll, thermal direct',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Fragile Sticker Pack',
      code: 'STK-FRG-001',
      category: 'supplies',
      type: 'fragile_stickers',
      size: 's',
      dimensions: '10x10 cm',
      weight: '200g',
      stockQuantity: 150,
      minStockLevel: 30,
      cost: '4.50',
      currency: 'EUR',
      supplier: 'Label Solutions Pro',
      description: 'Red FRAGILE warning stickers, 100 pack',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Packing List Envelopes',
      code: 'ENV-PKL-001',
      category: 'supplies',
      type: 'packing_list_envelopes',
      size: 'm',
      dimensions: 'A5 (15x21 cm)',
      weight: '10g each',
      stockQuantity: 1000,
      minStockLevel: 200,
      cost: '0.08',
      currency: 'EUR',
      supplier: 'Office Supplies Direct',
      description: 'Self-adhesive document pouches',
      isFragile: false,
      isReusable: false,
      isActive: true,
    },
    {
      name: 'Industrial Packing Gloves',
      code: 'GLV-IND-001',
      category: 'supplies',
      type: 'gloves',
      size: 'l',
      dimensions: 'Size L (Large)',
      weight: '120g per pair',
      stockQuantity: 250,
      minStockLevel: 50,
      cost: '1.20',
      currency: 'EUR',
      supplier: 'Safety First Ltd',
      description: 'Cut-resistant packing gloves',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
    {
      name: 'Permanent Markers Pack',
      code: 'MRK-PRM-001',
      category: 'supplies',
      type: 'markers',
      size: 's',
      dimensions: 'Standard',
      weight: '150g',
      stockQuantity: 100,
      minStockLevel: 20,
      cost: '3.50',
      currency: 'EUR',
      supplier: 'Office Supplies Direct',
      description: 'Black permanent markers, 10 pack',
      isFragile: false,
      isReusable: true,
      isActive: true,
    },
  ];

  try {
    // Check if materials already exist
    const existingMaterials = await db.select().from(packingMaterials).limit(1);
    
    if (existingMaterials.length > 0) {
      console.log('Packing materials already seeded. Skipping...');
      return;
    }

    // Insert all materials
    for (const material of materials) {
      await db.insert(packingMaterials).values(material);
    }

    console.log(`✅ Successfully seeded ${materials.length} packing materials`);
  } catch (error) {
    console.error('Error seeding packing materials:', error);
    throw error;
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedPackingMaterials()
    .then(() => {
      console.log('Seeding completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seeding failed:', error);
      process.exit(1);
    });
}
