const discounts = {
  // Page titles
  pageTitle: 'Discount Management',
  pageSubtitle: 'Manage promotional discounts and special offers',
  addPageTitle: 'Add New Discount',
  addPageSubtitle: 'Create promotional discounts for your products',
  editPageTitle: 'Edit Discount',
  
  // Navigation
  backToDiscounts: 'Back to Discounts',
  
  // Stats
  totalDiscounts: 'Total Discounts',
  activeDiscounts: 'Active',
  expiredDiscounts: 'Expired',
  wideScopeOffers: 'Wide-Scope Offers',
  discountsApplyingToMultiple: '{{count}} discounts applying to multiple products',
  
  // Table headers
  code: 'Code',
  discount: 'Discount',
  type: 'Type',
  value: 'Value',
  scope: 'Scope',
  validFrom: 'Valid From',
  validTo: 'Valid To',
  minPurchase: 'Min Purchase',
  maxUses: 'Max Uses',
  
  // Discount types
  percentage: 'Percentage',
  percentageOff: 'Percentage Off',
  fixedAmount: 'Fixed Amount',
  fixedAmountOff: 'Fixed Amount Off',
  buyXGetY: 'Buy X Get Y',
  freeShipping: 'Free Shipping',
  
  // Discount type descriptions
  discountType: 'Discount Type',
  discountByPercentage: 'Discount by percentage',
  fixedDiscountAmount: 'Fixed discount amount',
  buyXItemsGetYFree: 'Buy X items, get Y free',
  percentageDesc: 'Discount by percentage',
  fixedAmountDesc: 'Fixed discount amount',
  buyXGetYDesc: 'Buy X items, get Y free',
  
  // Application scope
  specificProduct: 'Specific Product',
  allProducts: 'All Products',
  specificCategory: 'Specific Category',
  selectedProducts: 'Selected Products',
  scopeProduct: 'Product',
  scopeAll: 'All',
  scopeCategory: 'Category',
  scopeSelected: 'Selected',
  
  // Status
  active: 'Active',
  inactive: 'Inactive',
  finished: 'Finished',
  expired: 'Expired',
  scheduled: 'Scheduled',
  
  // Buttons
  addDiscount: 'Add Discount',
  createDiscount: 'Create Discount',
  updateDiscount: 'Update Discount',
  deleteDiscount: 'Delete Discount',
  saveAsDraft: 'Save as Draft',
  activate: 'Activate',
  deactivate: 'Deactivate',
  duplicate: 'Duplicate',
  
  // Bulk actions
  activateSales: 'Activate Sales',
  deactivateSales: 'Deactivate Sales',
  activatingCount: 'Activating {{count}} sales...',
  deactivatingCount: 'Deactivating {{count}} sales...',
  exportingCount: 'Exporting {{count}} discounts...',
  
  // Form sections
  basicInformation: 'Basic Information',
  basicInfo: 'Basic Information',
  discountTypeValue: 'Discount Type & Value',
  applicationScope: 'Application Scope',
  
  // Edit/Add page headings
  editDiscount: 'Edit Discount',
  addDiscountPageTitle: 'Add New Discount',
  discountSummary: 'Discount Summary',
  advancedOptions: 'Advanced Options',
  discountRules: 'Discount Rules',
  usageLimits: 'Usage Limits',
  validityPeriod: 'Validity Period',
  
  // Form fields
  discountId: 'Discount ID',
  discountName: 'Discount Name',
  description: 'Description',
  startDate: 'Start Date',
  endDate: 'End Date',
  discountPercentage: 'Discount Percentage',
  discountAmount: 'Discount Amount',
  autoGenerated: 'Auto-generated',
  generatedFromNameAndDate: 'Generated from name and date',
  buyQuantity: 'Buy Quantity',
  getQuantity: 'Get Quantity',
  getFreeProduct: 'Get Free Product',
  sameProduct: 'Same Product',
  differentProduct: 'Different Product',
  selectProduct: 'Select Product',
  selectCategory: 'Select Category',
  selectProductsToDiscount: 'Select Products to Discount',
  searchProducts: 'Search products...',
  searchCategories: 'Search categories...',
  noProducts: 'No products found',
  noCategories: 'No categories found',
  
  // Placeholders
  placeholderName: 'e.g., Summer Sale 2024',
  placeholderDescription: 'Describe the discount and its terms...',
  placeholderPercentage: '10',
  placeholderFixedAmount: '120.00',
  placeholderFixedAmountCzk: '120',
  placeholderFixedAmountEur: '4.80',
  placeholderBuyQuantity: '2',
  placeholderGetQuantity: '1',
  
  // Validation messages
  nameRequired: 'Discount name is required',
  startDateRequired: 'Start date is required',
  endDateRequired: 'End date is required',
  percentageRequired: 'Percentage is required',
  fixedAmountRequired: 'Fixed amount is required',
  productRequired: 'Product is required',
  categoryRequired: 'Category is required',
  fillRequiredFields: 'Please fill in all required fields for the selected discount type and scope',
  pleaseFixErrors: 'Please fix the following errors before submitting:',
  
  // Tooltips
  tooltipDiscounts: '{{count}} discounts',
  tooltipActive: '{{count}} active discounts',
  tooltipExpired: '{{count}} expired discounts',
  
  // Product selection
  addProduct: 'Add Product',
  removeProduct: 'Remove Product',
  productsSelected: '{{count}} products selected',
  alreadySelected: 'Already selected',
  productInList: 'Product {{count}}',
  productsInCategory: '{{count}} products',
  
  // Scope selection messages
  selectScopeFirst: 'Please select an application scope first',
  selectProductFirst: 'Select a product to apply this discount',
  selectCategoryFirst: 'Select a category to apply this discount',
  selectProductsFirst: 'Select products to apply this discount',
  allProductsSelected: 'This discount applies to all products',
  appliesTo: 'Applies to',
  
  // Buy X Get Y options
  customerGets: 'Customer Gets',
  sameProductFree: 'Same product free',
  differentProductFree: 'Different product free',
  
  // Advanced options
  autoConversion: 'Auto-conversion after 1.5 seconds',
  approxRate: 'Approximate rate: 1 EUR = 25 CZK',
  
  // Messages
  loadingDiscounts: 'Loading discounts...',
  failedToLoad: 'Failed to load discounts',
  discountCreated: 'Discount created successfully',
  discountUpdated: 'Discount updated successfully',
  discountDeleted: 'Discount deleted successfully',
  discountDuplicated: 'Discount duplicated successfully',
  failedToCreate: 'Failed to create discount',
  failedToUpdate: 'Failed to update discount',
  failedToDelete: 'Failed to delete discount',
  cannotDelete: 'Cannot delete discount - it\'s being used in existing records',
  deletedCount: 'Deleted {{count}} discount(s) successfully',
  
  // Export
  exportReport: 'Discounts Report',
  exportFilename: 'Discounts_{{date}}',
  exportedToXLSX: 'Exported {{count}} discount(s) to XLSX',
  exportedToPDF: 'Exported {{count}} discount(s) to PDF',
  exportFailed: 'Failed to export discounts',
  exportFailedXLSX: 'Failed to export discounts to XLSX',
  exportFailedPDF: 'Failed to export discounts to PDF',
  
  // Export columns
  exportCode: 'Code',
  exportDescription: 'Description',
  exportType: 'Type',
  exportValue: 'Value',
  exportMinPurchase: 'Min Purchase',
  exportMaxUses: 'Max Uses',
  exportValidFrom: 'Valid From',
  exportValidUntil: 'Valid Until',
  exportStatus: 'Status',
  unlimited: 'Unlimited',
  buyXGetYFormat: 'B{{buy}}G{{get}}',
  
  // Empty states
  noDiscounts: 'No discounts found',
  noDiscountsDescription: 'Get started by creating your first discount',
  
  // Delete confirmation
  deleteConfirmTitle: 'Delete Discount',
  deleteConfirmDescription: 'Are you sure you want to delete this discount? This action cannot be undone.',
  deleteConfirmMultiple: 'Are you sure you want to delete {{count}} discount(s)? This action cannot be undone.',
  
  // Currency
  currencyCZK: 'CZK',
  currencyEUR: 'EUR',
  
  // Required field marker
  required: '*',
  
  // Column visibility
  toggleColumns: 'Toggle Columns',
  
  // Additional display fields (used in AllDiscounts card view)
  usageLimit: 'Usage Limit',
  usesCount: '{{count}} uses',
  none: 'None',
  restrictions: 'Restrictions',
  noDiscountsFound: 'No discounts found',
  tryAdjustingSearch: 'Try adjusting your search or filters',
  deleteDiscounts: 'Delete Discounts',
  confirmDelete: 'Are you sure you want to delete {{count}} discount(s)?',
  
  // Edit/Add page summary
  enterName: 'Enter discount name',
  discountValue: 'Discount Value',
  itemPrice: 'Item Price',
  finalPrice: 'Final Price',
  promotion: 'Promotion',
  buyGetFree: 'Buy {{buy}}, Get {{get}} Free',
  effectiveDiscount: 'Effective Discount',
  onTotalItems: 'on {{total}} total items',
} as const;

export default discounts;
